[package]
name = "pallet-society"
version = "28.0.0"
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
homepage = "https://substrate.io"
repository.workspace = true
description = "FRAME society pallet"
readme = "README.md"

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
log = { version = "0.4.17", default-features = false }
rand_chacha = { version = "0.2", default-features = false }
scale-info = { version = "2.10.0", default-features = false, features = ["derive"] }
codec = { package = "parity-scale-codec", version = "3.6.1", default-features = false, features = ["derive"] }

sp-std = { path = "../../primitives/std", default-features = false, version = "14.0.0" }
sp-io = { path = "../../primitives/io", default-features = false, version = "30.0.0" }
sp-arithmetic = { path = "../../primitives/arithmetic", default-features = false, version = "23.0.0" }
sp-runtime = { path = "../../primitives/runtime", default-features = false, version = "31.0.0" }
frame-benchmarking = { path = "../benchmarking", default-features = false, optional = true, version = "28.0.0" }
frame-support = { path = "../support", default-features = false, version = "28.0.0" }
frame-system = { path = "../system", default-features = false, version = "28.0.0" }

[dev-dependencies]
frame-support-test = { path = "../support/test" }
pallet-balances = { path = "../balances" }
sp-core = { path = "../../primitives/core" }
sp-io = { path = "../../primitives/io" }

[features]
default = ["std"]
std = [
	"codec/std",
	"frame-benchmarking?/std",
	"frame-support/std",
	"frame-system/std",
	"log/std",
	"rand_chacha/std",
	"scale-info/std",
	"sp-arithmetic/std",
	"sp-io/std",
	"sp-runtime/std",
	"sp-std/std",
]
runtime-benchmarks = [
	"frame-benchmarking",
	"frame-benchmarking/runtime-benchmarks",
	"frame-support/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
]
try-runtime = [
	"frame-support/try-runtime",
	"frame-system/try-runtime",
	"sp-runtime/try-runtime",
]
