[package]
description = "Substrate transaction protocol"
name = "sc-network-transactions"
version = "0.33.0"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
authors.workspace = true
edition.workspace = true
homepage = "https://substrate.io"
repository.workspace = true
documentation = "https://docs.rs/sc-network-transactions"

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
array-bytes = "6.1"
codec = { package = "parity-scale-codec", version = "3.6.1", features = ["derive"] }
futures = "0.3.21"
libp2p = "0.51.4"
log = "0.4.17"
prometheus-endpoint = { package = "substrate-prometheus-endpoint", path = "../../../utils/prometheus", version = "0.17.0" }
sc-network = { version = "0.34.0", path = ".." }
sc-network-common = { version = "0.33.0", path = "../common" }
sc-network-sync = { version = "0.33.0", path = "../sync" }
sc-utils = { version = "14.0.0", path = "../../utils" }
sp-runtime = { version = "31.0.0", path = "../../../primitives/runtime" }
sp-consensus = { version = "0.32.0", path = "../../../primitives/consensus/common" }
