[package]
name = "sp-consensus"
version = "0.32.0"
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
homepage = "https://substrate.io"
repository.workspace = true
description = "Common utilities for building and using consensus engines in substrate."
documentation = "https://docs.rs/sp-consensus/"
readme = "README.md"

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
async-trait = "0.1.74"
futures = { version = "0.3.21", features = ["thread-pool"] }
log = "0.4.17"
thiserror = "1.0.48"
sp-core = { version = "28.0.0", path = "../../core" }
sp-inherents = { version = "26.0.0", path = "../../inherents" }
sp-runtime = { version = "31.0.0", path = "../../runtime" }
sp-state-machine = { version = "0.35.0", path = "../../state-machine" }

[dev-dependencies]
futures = "0.3.21"
sp-test-primitives = { path = "../../test-primitives" }

[features]
default = []
