[package]
name = "pallet-session-benchmarking"
version = "28.0.0"
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
homepage = "https://substrate.io"
repository.workspace = true
description = "FRAME sessions pallet benchmarking"
readme = "README.md"

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "3.6.1", default-features = false }
rand = { version = "0.8.5", default-features = false, features = ["std_rng"] }
frame-benchmarking = { path = "../../benchmarking", default-features = false, version = "28.0.0" }
frame-support = { path = "../../support", default-features = false, version = "28.0.0" }
frame-system = { path = "../../system", default-features = false, version = "28.0.0" }
pallet-session = { path = "..", default-features = false, version = "28.0.0" }
pallet-staking = { path = "../../staking", default-features = false, version = "28.0.1" }
sp-runtime = { path = "../../../primitives/runtime", default-features = false, version = "31.0.0" }
sp-session = { path = "../../../primitives/session", default-features = false, version = "27.0.0" }
sp-std = { path = "../../../primitives/std", default-features = false, version = "14.0.0" }

[dev-dependencies]
codec = { package = "parity-scale-codec", version = "3.6.1", features = ["derive"] }
scale-info = "2.10.0"
frame-election-provider-support = { path = "../../election-provider-support" }
pallet-balances = { path = "../../balances" }
pallet-staking-reward-curve = { path = "../../staking/reward-curve" }
pallet-timestamp = { path = "../../timestamp" }
sp-core = { path = "../../../primitives/core" }
sp-io = { path = "../../../primitives/io" }

[features]
default = ["std"]
std = [
	"frame-benchmarking/std",
	"frame-support/std",
	"frame-system/std",
	"pallet-session/std",
	"pallet-staking/std",
	"rand/std",
	"sp-runtime/std",
	"sp-session/std",
	"sp-std/std",
]

runtime-benchmarks = [
	"frame-benchmarking/runtime-benchmarks",
	"frame-support/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
	"pallet-staking/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
]
