[package]
name = "substrate-rpc-client"
version = "0.33.0"
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
homepage = "https://substrate.io"
repository.workspace = true
description = "Shared JSON-RPC client"

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
jsonrpsee = { version = "0.16.2", features = ["ws-client"] }
sc-rpc-api = { version = "0.33.0", path = "../../../../client/rpc-api" }
async-trait = "0.1.74"
serde = "1"
sp-runtime = { version = "31.0.0", path = "../../../../primitives/runtime" }
log = "0.4"

[dev-dependencies]
tokio = { version = "1.22.0", features = ["macros", "rt-multi-thread", "sync"] }
sp-core = { path = "../../../../primitives/core" }
