[package]
name = "sc-consensus-manual-seal"
version = "0.35.0"
authors.workspace = true
description = "Manual sealing engine for Substrate"
edition.workspace = true
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
homepage = "https://substrate.io"
repository.workspace = true
readme = "README.md"

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
jsonrpsee = { version = "0.16.2", features = ["client-core", "macros", "server"] }
assert_matches = "1.3.0"
async-trait = "0.1.74"
codec = { package = "parity-scale-codec", version = "3.6.1" }
futures = "0.3.21"
futures-timer = "3.0.1"
log = "0.4.17"
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"
prometheus-endpoint = { package = "substrate-prometheus-endpoint", path = "../../../utils/prometheus", version = "0.17.0" }
sc-client-api = { version = "28.0.0", path = "../../api" }
sc-consensus = { version = "0.33.0", path = "../common" }
sc-consensus-aura = { version = "0.34.0", path = "../aura" }
sc-consensus-babe = { version = "0.34.0", path = "../babe" }
sc-consensus-epochs = { version = "0.33.0", path = "../epochs" }
sc-transaction-pool = { version = "28.0.0", path = "../../transaction-pool" }
sc-transaction-pool-api = { version = "28.0.0", path = "../../transaction-pool/api" }
sp-api = { version = "26.0.0", path = "../../../primitives/api" }
sp-blockchain = { version = "28.0.0", path = "../../../primitives/blockchain" }
sp-consensus = { version = "0.32.0", path = "../../../primitives/consensus/common" }
sp-consensus-aura = { version = "0.32.0", path = "../../../primitives/consensus/aura" }
sp-consensus-babe = { version = "0.32.0", path = "../../../primitives/consensus/babe" }
sp-consensus-slots = { version = "0.32.0", path = "../../../primitives/consensus/slots" }
sp-core = { version = "28.0.0", path = "../../../primitives/core" }
sp-inherents = { version = "26.0.0", path = "../../../primitives/inherents" }
sp-keystore = { version = "0.34.0", path = "../../../primitives/keystore" }
sp-runtime = { version = "31.0.0", path = "../../../primitives/runtime" }
sp-timestamp = { version = "26.0.0", path = "../../../primitives/timestamp" }

[dev-dependencies]
tokio = { version = "1.22.0", features = ["macros", "rt-multi-thread"] }
sc-basic-authorship = { path = "../../basic-authorship" }
substrate-test-runtime-client = { path = "../../../test-utils/runtime/client" }
substrate-test-runtime-transaction-pool = { path = "../../../test-utils/runtime/transaction-pool" }
