[package]
name = "pallet-beefy-mmr"
version = "28.0.0"
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
description = "BEEFY + MMR runtime utilities"
repository.workspace = true
homepage = "https://substrate.io"

[lints]
workspace = true

[dependencies]
array-bytes = { version = "6.1", optional = true }
codec = { package = "parity-scale-codec", version = "3.6.1", default-features = false, features = ["derive"] }
log = { version = "0.4.17", default-features = false }
scale-info = { version = "2.10.0", default-features = false, features = ["derive"] }
serde = { version = "1.0.195", optional = true }
binary-merkle-tree = { path = "../../utils/binary-merkle-tree", default-features = false, version = "13.0.0" }
frame-support = { path = "../support", default-features = false, version = "28.0.0" }
frame-system = { path = "../system", default-features = false, version = "28.0.0" }
pallet-beefy = { path = "../beefy", default-features = false, version = "28.0.0" }
pallet-mmr = { path = "../merkle-mountain-range", default-features = false, version = "27.0.0" }
pallet-session = { path = "../session", default-features = false, version = "28.0.0" }
sp-consensus-beefy = { path = "../../primitives/consensus/beefy", default-features = false, version = "13.0.0" }
sp-core = { path = "../../primitives/core", default-features = false, version = "28.0.0" }
sp-io = { path = "../../primitives/io", default-features = false, version = "30.0.0" }
sp-runtime = { path = "../../primitives/runtime", default-features = false, version = "31.0.0" }
sp-std = { path = "../../primitives/std", default-features = false, version = "14.0.0" }
sp-api = { path = "../../primitives/api", default-features = false, version = "26.0.0" }
sp-state-machine = { path = "../../primitives/state-machine", default-features = false, version = "0.35.0" }

[dev-dependencies]
array-bytes = "6.1"
sp-staking = { path = "../../primitives/staking" }

[features]
default = ["std"]
std = [
	"array-bytes",
	"binary-merkle-tree/std",
	"codec/std",
	"frame-support/std",
	"frame-system/std",
	"log/std",
	"pallet-beefy/std",
	"pallet-mmr/std",
	"pallet-session/std",
	"scale-info/std",
	"serde",
	"sp-api/std",
	"sp-consensus-beefy/std",
	"sp-core/std",
	"sp-io/std",
	"sp-runtime/std",
	"sp-state-machine/std",
	"sp-std/std",
]
try-runtime = [
	"frame-support/try-runtime",
	"frame-system/try-runtime",
	"pallet-beefy/try-runtime",
	"pallet-mmr/try-runtime",
	"pallet-session/try-runtime",
	"sp-runtime/try-runtime",
]
