[package]
name = "sp-runtime-interface-test-wasm-deprecated"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
build = "build.rs"
license = "Apache-2.0"
homepage = "https://substrate.io"
repository.workspace = true
publish = false
description = "sp-runtime-interface-test-wasm-deprecated"

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
sp-core = { path = "../../core", default-features = false, version = "28.0.0" }
sp-io = { path = "../../io", default-features = false, version = "30.0.0" }
sp-runtime-interface = { path = "..", default-features = false, version = "24.0.0" }

[build-dependencies]
substrate-wasm-builder = { path = "../../../utils/wasm-builder", optional = true, version = "17.0.0" }

[features]
default = ["std"]
std = [
	"sp-core/std",
	"sp-io/std",
	"sp-runtime-interface/std",
	"substrate-wasm-builder",
]
