[package]
name = "pallet-asset-tx-payment"
version = "28.0.0"
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
homepage = "https://substrate.io"
repository.workspace = true
description = "pallet to manage transaction payments in assets"
readme = "README.md"

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
# Substrate dependencies
sp-core = { path = "../../../primitives/core", default-features = false, version = "28.0.0" }
sp-io = { path = "../../../primitives/io", default-features = false, version = "30.0.0" }
sp-runtime = { path = "../../../primitives/runtime", default-features = false, version = "31.0.0" }
sp-std = { path = "../../../primitives/std", default-features = false, version = "14.0.0" }

frame-support = { path = "../../support", default-features = false, version = "28.0.0" }
frame-system = { path = "../../system", default-features = false, version = "28.0.0" }
pallet-transaction-payment = { path = "..", default-features = false, version = "28.0.0" }
frame-benchmarking = { path = "../../benchmarking", default-features = false, optional = true, version = "28.0.0" }

# Other dependencies
codec = { package = "parity-scale-codec", version = "3.6.1", default-features = false, features = ["derive"] }
scale-info = { version = "2.10.0", default-features = false, features = ["derive"] }
serde = { version = "1.0.195", optional = true }

[dev-dependencies]
serde_json = "1.0.111"

sp-storage = { path = "../../../primitives/storage", default-features = false }
pallet-assets = { path = "../../assets" }
pallet-authorship = { path = "../../authorship" }
pallet-balances = { path = "../../balances" }

[features]
default = ["std"]
std = [
	"codec/std",
	"frame-benchmarking?/std",
	"frame-support/std",
	"frame-system/std",
	"pallet-transaction-payment/std",
	"scale-info/std",
	"serde",
	"sp-core/std",
	"sp-io/std",
	"sp-runtime/std",
	"sp-std/std",
]
runtime-benchmarks = [
	"frame-benchmarking/runtime-benchmarks",
	"frame-support/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
]
try-runtime = [
	"frame-support/try-runtime",
	"frame-system/try-runtime",
	"pallet-transaction-payment/try-runtime",
	"sp-runtime/try-runtime",
]
