[package]
name = "sp-test-primitives"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
homepage = "https://substrate.io"
repository.workspace = true
publish = false
description = "sp-test-primitives"

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "3.6.1", default-features = false, features = ["derive"] }
scale-info = { version = "2.10.0", default-features = false, features = ["derive"] }
serde = { version = "1.0.195", default-features = false, features = ["derive"], optional = true }
sp-application-crypto = { path = "../application-crypto", default-features = false, version = "30.0.0" }
sp-core = { path = "../core", default-features = false, version = "28.0.0" }
sp-runtime = { path = "../runtime", default-features = false, version = "31.0.0" }
sp-std = { path = "../std", default-features = false, version = "14.0.0" }

[features]
default = ["std"]
std = [
	"codec/std",
	"scale-info/std",
	"serde/std",
	"sp-application-crypto/std",
	"sp-core/std",
	"sp-runtime/std",
	"sp-std/std",
]

# Serde support without relying on std features.
serde = [
	"dep:serde",
	"sp-application-crypto/serde",
	"sp-core/serde",
	"sp-runtime/serde",
]
