[package]
name = "substrate-test-runtime-client"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
homepage = "https://substrate.io"
repository.workspace = true
publish = false
description = "substrate-test-runtime-client"

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
futures = "0.3.21"
sc-block-builder = { version = "0.33.0", path = "../../../client/block-builder" }
sc-client-api = { version = "28.0.0", path = "../../../client/api" }
sc-consensus = { version = "0.33.0", path = "../../../client/consensus/common" }
sp-api = { version = "26.0.0", path = "../../../primitives/api" }
sp-blockchain = { version = "28.0.0", path = "../../../primitives/blockchain" }
sp-consensus = { version = "0.32.0", path = "../../../primitives/consensus/common" }
sp-core = { version = "28.0.0", path = "../../../primitives/core" }
sp-runtime = { version = "31.0.0", path = "../../../primitives/runtime" }
substrate-test-client = { version = "0.1.0", path = "../../client" }
substrate-test-runtime = { version = "0.1.0", path = ".." }
