[package]
name = "pallet-offences-benchmarking"
version = "28.0.0"
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
homepage = "https://substrate.io"
repository.workspace = true
description = "FRAME offences pallet benchmarking"
readme = "README.md"

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "3.6.1", default-features = false }
scale-info = { version = "2.10.0", default-features = false, features = ["derive"] }
frame-benchmarking = { path = "../../benchmarking", default-features = false, version = "28.0.0" }
frame-election-provider-support = { path = "../../election-provider-support", default-features = false, version = "28.0.0" }
frame-support = { path = "../../support", default-features = false, version = "28.0.0" }
frame-system = { path = "../../system", default-features = false, version = "28.0.0" }
pallet-babe = { path = "../../babe", default-features = false, version = "28.0.0" }
pallet-balances = { path = "../../balances", default-features = false, version = "28.0.0" }
pallet-grandpa = { path = "../../grandpa", default-features = false, version = "28.0.0" }
pallet-im-online = { path = "../../im-online", default-features = false, version = "27.0.0" }
pallet-offences = { path = "..", default-features = false, version = "27.0.0" }
pallet-session = { path = "../../session", default-features = false, version = "28.0.0" }
pallet-staking = { path = "../../staking", default-features = false, version = "28.0.1" }
sp-runtime = { path = "../../../primitives/runtime", default-features = false, version = "31.0.0" }
sp-staking = { path = "../../../primitives/staking", default-features = false, version = "26.0.0" }
sp-std = { path = "../../../primitives/std", default-features = false, version = "14.0.0" }
log = { version = "0.4.17", default-features = false }

[dev-dependencies]
pallet-staking-reward-curve = { path = "../../staking/reward-curve" }
pallet-timestamp = { path = "../../timestamp" }
sp-core = { path = "../../../primitives/core" }
sp-io = { path = "../../../primitives/io" }

[features]
default = ["std"]
std = [
	"codec/std",
	"frame-benchmarking/std",
	"frame-election-provider-support/std",
	"frame-support/std",
	"frame-system/std",
	"log/std",
	"pallet-babe/std",
	"pallet-balances/std",
	"pallet-grandpa/std",
	"pallet-im-online/std",
	"pallet-offences/std",
	"pallet-session/std",
	"pallet-staking/std",
	"scale-info/std",
	"sp-runtime/std",
	"sp-staking/std",
	"sp-std/std",
]

runtime-benchmarks = [
	"frame-benchmarking/runtime-benchmarks",
	"frame-election-provider-support/runtime-benchmarks",
	"frame-support/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
	"pallet-babe/runtime-benchmarks",
	"pallet-balances/runtime-benchmarks",
	"pallet-grandpa/runtime-benchmarks",
	"pallet-im-online/runtime-benchmarks",
	"pallet-offences/runtime-benchmarks",
	"pallet-staking/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
	"sp-staking/runtime-benchmarks",
]
