[package]
name = "sp-block-builder"
version = "26.0.0"
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
homepage = "https://substrate.io"
repository.workspace = true
description = "The block builder runtime api."
readme = "README.md"

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
sp-api = { path = "../api", default-features = false, version = "26.0.0" }
sp-inherents = { path = "../inherents", default-features = false, version = "26.0.0" }
sp-runtime = { path = "../runtime", default-features = false, version = "31.0.0" }
sp-std = { path = "../std", default-features = false, version = "14.0.0" }

[features]
default = ["std"]
std = ["sp-api/std", "sp-inherents/std", "sp-runtime/std", "sp-std/std"]
