[package]
name = "substrate-test-runtime"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
build = "build.rs"
license = "Apache-2.0"
homepage = "https://substrate.io"
repository.workspace = true
publish = false
description = "substrate-test-runtime"

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
sp-application-crypto = { path = "../../primitives/application-crypto", default-features = false, features = ["serde"], version = "30.0.0" }
sp-consensus-aura = { path = "../../primitives/consensus/aura", default-features = false, features = ["serde"], version = "0.32.0" }
sp-consensus-babe = { path = "../../primitives/consensus/babe", default-features = false, features = ["serde"], version = "0.32.0" }
sp-genesis-builder = { path = "../../primitives/genesis-builder", default-features = false, version = "0.7.0" }
sp-block-builder = { path = "../../primitives/block-builder", default-features = false, version = "26.0.0" }
codec = { package = "parity-scale-codec", version = "3.6.1", default-features = false, features = ["derive"] }
scale-info = { version = "2.10.0", default-features = false, features = ["derive"] }
sp-inherents = { path = "../../primitives/inherents", default-features = false, version = "26.0.0" }
sp-keyring = { path = "../../primitives/keyring", optional = true, version = "31.0.0" }
sp-offchain = { path = "../../primitives/offchain", default-features = false, version = "26.0.0" }
sp-core = { path = "../../primitives/core", default-features = false, version = "28.0.0" }
sp-std = { path = "../../primitives/std", default-features = false, version = "14.0.0" }
sp-io = { path = "../../primitives/io", default-features = false, version = "30.0.0" }
frame-support = { path = "../../frame/support", default-features = false, version = "28.0.0" }
sp-version = { path = "../../primitives/version", default-features = false, version = "29.0.0" }
sp-session = { path = "../../primitives/session", default-features = false, version = "27.0.0" }
sp-api = { path = "../../primitives/api", default-features = false, version = "26.0.0" }
sp-runtime = { path = "../../primitives/runtime", default-features = false, features = ["serde"], version = "31.0.0" }
pallet-babe = { path = "../../frame/babe", default-features = false, version = "28.0.0" }
pallet-balances = { path = "../../frame/balances", default-features = false, version = "28.0.0" }
frame-executive = { path = "../../frame/executive", default-features = false, version = "28.0.0" }
frame-system = { path = "../../frame/system", default-features = false, version = "28.0.0" }
frame-system-rpc-runtime-api = { path = "../../frame/system/rpc/runtime-api", default-features = false, version = "26.0.0" }
pallet-timestamp = { path = "../../frame/timestamp", default-features = false, version = "27.0.0" }
sp-consensus-grandpa = { path = "../../primitives/consensus/grandpa", default-features = false, features = ["serde"], version = "13.0.0" }
sp-trie = { path = "../../primitives/trie", default-features = false, version = "29.0.0" }
sp-transaction-pool = { path = "../../primitives/transaction-pool", default-features = false, version = "26.0.0" }
trie-db = { version = "0.28.0", default-features = false }
sc-service = { path = "../../client/service", default-features = false, features = ["test-helpers"], optional = true, version = "0.35.0" }
sp-state-machine = { path = "../../primitives/state-machine", default-features = false, version = "0.35.0" }
sp-externalities = { path = "../../primitives/externalities", default-features = false, version = "0.25.0" }

# 3rd party
array-bytes = { version = "6.1", optional = true }
log = { version = "0.4.17", default-features = false }

[dev-dependencies]
futures = "0.3.21"
sc-block-builder = { path = "../../client/block-builder" }
sc-executor = { path = "../../client/executor" }
sc-executor-common = { path = "../../client/executor/common" }
sp-consensus = { path = "../../primitives/consensus/common" }
substrate-test-runtime-client = { path = "client" }
sp-tracing = { path = "../../primitives/tracing" }
json-patch = { version = "1.0.0", default-features = false }
serde = { version = "1.0.195", features = ["alloc", "derive"], default-features = false }
serde_json = { version = "1.0.111", default-features = false, features = ["alloc"] }

[build-dependencies]
substrate-wasm-builder = { path = "../../utils/wasm-builder", optional = true, version = "17.0.0" }

[features]
default = ["std"]

std = [
	"array-bytes",
	"codec/std",
	"frame-executive/std",
	"frame-support/std",
	"frame-system-rpc-runtime-api/std",
	"frame-system/std",
	"log/std",
	"pallet-babe/std",
	"pallet-balances/std",
	"pallet-timestamp/std",
	"sc-service",
	"scale-info/std",
	"sp-api/std",
	"sp-application-crypto/std",
	"sp-block-builder/std",
	"sp-consensus-aura/std",
	"sp-consensus-babe/std",
	"sp-consensus-grandpa/std",
	"sp-core/std",
	"sp-externalities/std",
	"sp-genesis-builder/std",
	"sp-inherents/std",
	"sp-io/std",
	"sp-keyring",
	"sp-offchain/std",
	"sp-runtime/std",
	"sp-session/std",
	"sp-state-machine/std",
	"sp-std/std",
	"sp-transaction-pool/std",
	"sp-trie/std",
	"sp-version/std",
	"substrate-wasm-builder",
	"trie-db/std",
]
# Special feature to disable logging
disable-logging = ["sp-api/disable-logging"]
