[package]
name = "node-testing"
version = "0.1.0"
authors.workspace = true
description = "Test utilities for Substrate node."
edition.workspace = true
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
homepage = "https://substrate.io"
repository.workspace = true
publish = false

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "3.6.1" }
fs_extra = "1"
futures = "0.3.21"
log = "0.4.17"
tempfile = "3.1.0"
frame-system = { version = "28.0.0", path = "../../../frame/system" }
node-cli = { package = "staging-node-cli", path = "../cli", version = "0.1.0" }
node-primitives = { version = "2.0.0", path = "../primitives" }
kitchensink-runtime = { version = "0.1.0", path = "../runtime" }
pallet-asset-conversion = { version = "10.0.0", path = "../../../frame/asset-conversion" }
pallet-assets = { version = "29.0.0", path = "../../../frame/assets" }
pallet-asset-conversion-tx-payment = { version = "10.0.0", path = "../../../frame/transaction-payment/asset-conversion-tx-payment" }
pallet-asset-tx-payment = { version = "28.0.0", path = "../../../frame/transaction-payment/asset-tx-payment" }
pallet-skip-feeless-payment = { version = "3.0.0", path = "../../../frame/transaction-payment/skip-feeless-payment" }
sc-block-builder = { version = "0.33.0", path = "../../../client/block-builder" }
sc-client-api = { version = "28.0.0", path = "../../../client/api" }
sc-client-db = { path = "../../../client/db", features = ["rocksdb"], version = "0.35.0" }
sc-consensus = { version = "0.33.0", path = "../../../client/consensus/common" }
sc-executor = { version = "0.32.0", path = "../../../client/executor" }
sc-service = { path = "../../../client/service", features = ["rocksdb", "test-helpers"], version = "0.35.0" }
sp-api = { version = "26.0.0", path = "../../../primitives/api" }
sp-block-builder = { version = "26.0.0", path = "../../../primitives/block-builder" }
sp-blockchain = { version = "28.0.0", path = "../../../primitives/blockchain" }
sp-consensus = { version = "0.32.0", path = "../../../primitives/consensus/common" }
sp-core = { version = "28.0.0", path = "../../../primitives/core" }
sp-inherents = { version = "26.0.0", path = "../../../primitives/inherents" }
sp-io = { version = "30.0.0", path = "../../../primitives/io" }
sp-keyring = { version = "31.0.0", path = "../../../primitives/keyring" }
sp-runtime = { version = "31.0.0", path = "../../../primitives/runtime" }
sp-timestamp = { path = "../../../primitives/timestamp", default-features = false, version = "26.0.0" }
substrate-test-client = { version = "0.1.0", path = "../../../test-utils/client" }
