[package]
name = "mmr-gadget"
version = "29.0.0"
authors.workspace = true
edition.workspace = true
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
repository.workspace = true
description = "MMR Client gadget for substrate"
homepage = "https://substrate.io"

[lints]
workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
codec = { package = "parity-scale-codec", version = "3.6.1" }
futures = "0.3"
log = "0.4"
sp-api = { version = "26.0.0", path = "../../primitives/api" }
sp-blockchain = { version = "28.0.0", path = "../../primitives/blockchain" }
sc-client-api = { version = "28.0.0", path = "../api" }
sp-consensus-beefy = { version = "13.0.0", path = "../../primitives/consensus/beefy" }
sp-consensus = { version = "0.32.0", path = "../../primitives/consensus/common" }
sp-core = { version = "28.0.0", path = "../../primitives/core" }
sp-mmr-primitives = { version = "26.0.0", path = "../../primitives/merkle-mountain-range" }
sc-offchain = { version = "29.0.0", path = "../offchain" }
sp-runtime = { version = "31.0.0", path = "../../primitives/runtime" }

[dev-dependencies]
parking_lot = "0.12.1"
sc-block-builder = { path = "../block-builder" }
sp-tracing = { path = "../../primitives/tracing" }
substrate-test-runtime-client = { path = "../../test-utils/runtime/client" }
tokio = "1.17.0"
