[package]
name = "sc-consensus-grandpa"
version = "0.19.0"
authors.workspace = true
edition.workspace = true
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
homepage = "https://substrate.io"
repository.workspace = true
description = "Integration of the GRANDPA finality gadget into substrate."
documentation = "https://docs.rs/sc-consensus-grandpa"
readme = "README.md"

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
ahash = "0.8.2"
array-bytes = "6.1"
async-trait = "0.1.74"
dyn-clone = "1.0"
finality-grandpa = { version = "0.16.2", features = ["derive-codec"] }
futures = "0.3.21"
futures-timer = "3.0.1"
log = "0.4.17"
parity-scale-codec = { version = "3.6.1", features = ["derive"] }
parking_lot = "0.12.1"
rand = "0.8.5"
serde_json = "1.0.111"
thiserror = "1.0"
fork-tree = { version = "12.0.0", path = "../../../utils/fork-tree" }
prometheus-endpoint = { package = "substrate-prometheus-endpoint", path = "../../../utils/prometheus", version = "0.17.0" }
sc-block-builder = { version = "0.33.0", path = "../../block-builder" }
sc-chain-spec = { version = "27.0.0", path = "../../chain-spec" }
sc-client-api = { version = "28.0.0", path = "../../api" }
sc-transaction-pool-api = { version = "28.0.0", path = "../../transaction-pool/api" }
sc-consensus = { version = "0.33.0", path = "../common" }
sc-network = { version = "0.34.0", path = "../../network" }
sc-network-gossip = { version = "0.34.0", path = "../../network-gossip" }
sc-network-common = { version = "0.33.0", path = "../../network/common" }
sc-network-sync = { version = "0.33.0", path = "../../network/sync" }
sc-telemetry = { version = "15.0.0", path = "../../telemetry" }
sc-utils = { version = "14.0.0", path = "../../utils" }
sp-api = { version = "26.0.0", path = "../../../primitives/api" }
sp-application-crypto = { version = "30.0.0", path = "../../../primitives/application-crypto" }
sp-arithmetic = { version = "23.0.0", path = "../../../primitives/arithmetic" }
sp-blockchain = { version = "28.0.0", path = "../../../primitives/blockchain" }
sp-consensus = { version = "0.32.0", path = "../../../primitives/consensus/common" }
sp-core = { version = "28.0.0", path = "../../../primitives/core" }
sp-consensus-grandpa = { version = "13.0.0", path = "../../../primitives/consensus/grandpa" }
sp-keystore = { version = "0.34.0", path = "../../../primitives/keystore" }
sp-runtime = { version = "31.0.0", path = "../../../primitives/runtime" }

[dev-dependencies]
assert_matches = "1.3.0"
finality-grandpa = { version = "0.16.2", features = ["derive-codec", "test-helpers"] }
serde = "1.0.195"
tokio = "1.22.0"
sc-network = { path = "../../network" }
sc-network-test = { path = "../../network/test" }
sp-keyring = { path = "../../../primitives/keyring" }
sp-tracing = { path = "../../../primitives/tracing" }
substrate-test-runtime-client = { path = "../../../test-utils/runtime/client" }
