[package]
name = "snowbridge-inbound-queue"
description = "Snowbridge Inbound Queue"
version = "0.1.0"
edition = "2021"
authors = ["Snowfork <contact@snowfork.com>"]
repository = "https://github.com/Snowfork/snowbridge"
license = "Apache-2.0"
publish = false

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
serde = { version = "1.0.195", optional = true }
codec = { version = "3.6.1", package = "parity-scale-codec", default-features = false, features = ["derive"] }
scale-info = { version = "2.9.0", default-features = false, features = ["derive"] }
hex-literal = { version = "0.4.1", optional = true }
log = { version = "0.4.20", default-features = false }
alloy-primitives = { version = "0.4.2", default-features = false, features = ["rlp"] }
alloy-sol-types = { version = "0.4.2", default-features = false }
alloy-rlp = { version = "0.3.3", default-features = false, features = ["derive"] }
num-traits = { version = "0.2.16", default-features = false }

frame-benchmarking = { path = "../../../../../substrate/frame/benchmarking", default-features = false, optional = true, version = "28.0.0" }
frame-support = { path = "../../../../../substrate/frame/support", default-features = false, version = "28.0.0" }
frame-system = { path = "../../../../../substrate/frame/system", default-features = false, version = "28.0.0" }
pallet-balances = { path = "../../../../../substrate/frame/balances", default-features = false, version = "28.0.0" }
sp-core = { path = "../../../../../substrate/primitives/core", default-features = false, version = "28.0.0" }
sp-std = { path = "../../../../../substrate/primitives/std", default-features = false, version = "14.0.0" }
sp-io = { path = "../../../../../substrate/primitives/io", default-features = false, version = "30.0.0" }
sp-runtime = { path = "../../../../../substrate/primitives/runtime", default-features = false, version = "31.0.0" }

xcm = { package = "staging-xcm", path = "../../../../../polkadot/xcm", default-features = false, version = "7.0.0" }
xcm-builder = { package = "staging-xcm-builder", path = "../../../../../polkadot/xcm/xcm-builder", default-features = false, version = "7.0.3" }

snowbridge-core = { path = "../../primitives/core", default-features = false, version = "0.1.0" }
snowbridge-ethereum = { path = "../../primitives/ethereum", default-features = false, version = "0.1.0" }
snowbridge-router-primitives = { path = "../../primitives/router", default-features = false, version = "0.1.0" }
snowbridge-beacon-primitives = { path = "../../primitives/beacon", default-features = false, optional = true, version = "0.1.0" }

[dev-dependencies]
frame-benchmarking = { path = "../../../../../substrate/frame/benchmarking" }
sp-keyring = { path = "../../../../../substrate/primitives/keyring" }
snowbridge-beacon-primitives = { path = "../../primitives/beacon" }
snowbridge-ethereum-beacon-client = { path = "../ethereum-beacon-client" }
hex-literal = { version = "0.4.1" }

[features]
default = ["std"]
std = [
	"alloy-primitives/std",
	"alloy-rlp/std",
	"alloy-sol-types/std",
	"codec/std",
	"frame-benchmarking/std",
	"frame-support/std",
	"frame-system/std",
	"log/std",
	"num-traits/std",
	"pallet-balances/std",
	"scale-info/std",
	"serde",
	"snowbridge-core/std",
	"snowbridge-ethereum/std",
	"snowbridge-router-primitives/std",
	"sp-core/std",
	"sp-io/std",
	"sp-runtime/std",
	"sp-std/std",
	"xcm-builder/std",
	"xcm/std",
]
runtime-benchmarks = [
	"frame-benchmarking",
	"frame-benchmarking/runtime-benchmarks",
	"frame-support/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
	"hex-literal",
	"pallet-balances/runtime-benchmarks",
	"snowbridge-beacon-primitives",
	"snowbridge-core/runtime-benchmarks",
	"snowbridge-router-primitives/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
	"xcm-builder/runtime-benchmarks",
]
try-runtime = [
	"frame-support/try-runtime",
	"frame-system/try-runtime",
	"pallet-balances/try-runtime",
	"sp-runtime/try-runtime",
]
