[package]
name = "cumulus-client-cli"
version = "0.7.0"
authors.workspace = true
edition.workspace = true
description = "Parachain node CLI utilities."
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"

[lints]
workspace = true

[dependencies]
clap = { version = "4.4.14", features = ["derive"] }
codec = { package = "parity-scale-codec", version = "3.0.0" }
url = "2.4.0"
sc-cli = { version = "0.36.0", path = "../../../substrate/client/cli" }
sc-client-api = { version = "28.0.0", path = "../../../substrate/client/api" }
sc-chain-spec = { version = "27.0.0", path = "../../../substrate/client/chain-spec" }
sc-service = { version = "0.35.0", path = "../../../substrate/client/service" }
sp-core = { version = "28.0.0", path = "../../../substrate/primitives/core" }
sp-runtime = { version = "31.0.0", path = "../../../substrate/primitives/runtime" }
sp-blockchain = { version = "28.0.0", path = "../../../substrate/primitives/blockchain" }
