[package]
name = "sc-runtime-test"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
build = "build.rs"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
publish = false
homepage = "https://substrate.io"
repository.workspace = true
description = "sc-runtime-test"

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
sp-core = { path = "../../../primitives/core", default-features = false, version = "28.0.0" }
sp-io = { path = "../../../primitives/io", default-features = false, features = ["improved_panic_error_reporting"], version = "30.0.0" }
sp-runtime = { path = "../../../primitives/runtime", default-features = false, version = "31.0.0" }
sp-runtime-interface = { path = "../../../primitives/runtime-interface", default-features = false, version = "24.0.0" }
sp-std = { path = "../../../primitives/std", default-features = false, version = "14.0.0" }

[build-dependencies]
substrate-wasm-builder = { path = "../../../utils/wasm-builder", optional = true, version = "17.0.0" }

[features]
default = ["std"]
std = [
	"sp-core/std",
	"sp-io/std",
	"sp-runtime-interface/std",
	"sp-runtime/std",
	"sp-std/std",
	"substrate-wasm-builder",
]
