[package]
name = "rococo-system-emulated-network"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
description = "Rococo System emulated network"
publish = false

[lints]
workspace = true

[dependencies]
# Cumulus
emulated-integration-tests-common = { path = "../../common", default-features = false, version = "3.0.0" }
rococo-emulated-chain = { version = "0.1.0", path = "../../chains/relays/rococo" }
asset-hub-rococo-emulated-chain = { version = "0.1.0", path = "../../chains/parachains/assets/asset-hub-rococo" }
bridge-hub-rococo-emulated-chain = { version = "0.1.0", path = "../../chains/parachains/bridges/bridge-hub-rococo" }
people-rococo-emulated-chain = { version = "0.1.0", path = "../../chains/parachains/people/people-rococo" }
penpal-emulated-chain = { version = "0.1.0", path = "../../chains/parachains/testing/penpal" }
