[package]
name = "test-parachain-adder-collator"
description = "Collator for the adder test parachain"
publish = false
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[[bin]]
name = "adder-collator"
path = "src/main.rs"

[dependencies]
parity-scale-codec = { version = "3.6.1", default-features = false, features = ["derive"] }
clap = { version = "4.4.14", features = ["derive"] }
futures = "0.3.21"
futures-timer = "3.0.2"
log = "0.4.17"
test-parachain-adder = { version = "0.0.0", path = ".." }
polkadot-primitives = { version = "7.0.0", path = "../../../../primitives" }
polkadot-cli = { version = "7.0.0", path = "../../../../cli" }
polkadot-service = { path = "../../../../node/service", features = ["rococo-native"], version = "7.0.0" }
polkadot-node-primitives = { version = "7.0.0", path = "../../../../node/primitives" }
polkadot-node-subsystem = { version = "7.0.0", path = "../../../../node/subsystem" }
sc-cli = { version = "0.36.0", path = "../../../../../substrate/client/cli" }
sp-core = { version = "28.0.0", path = "../../../../../substrate/primitives/core" }
sc-service = { version = "0.35.0", path = "../../../../../substrate/client/service" }

[dev-dependencies]
polkadot-parachain-primitives = { path = "../../.." }
polkadot-test-service = { path = "../../../../node/test/service" }
polkadot-node-core-pvf = { path = "../../../../node/core/pvf", features = ["test-utils"] }
substrate-test-utils = { path = "../../../../../substrate/test-utils" }
sc-service = { path = "../../../../../substrate/client/service" }
sp-keyring = { path = "../../../../../substrate/primitives/keyring" }

tokio = { version = "1.24.2", features = ["macros"] }
