[package]
authors.workspace = true
name = "cumulus-relay-chain-rpc-interface"
version = "0.7.0"
edition.workspace = true
description = "Implementation of the RelayChainInterface trait that connects to a remote RPC-node."
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"

[lints]
workspace = true

[dependencies]
polkadot-overseer = { version = "7.0.0", path = "../../../polkadot/node/overseer" }
cumulus-primitives-core = { version = "0.7.0", path = "../../primitives/core" }
cumulus-relay-chain-interface = { version = "0.7.0", path = "../relay-chain-interface" }
sp-api = { version = "26.0.0", path = "../../../substrate/primitives/api" }
sp-core = { version = "28.0.0", path = "../../../substrate/primitives/core" }
sp-consensus-babe = { version = "0.32.0", path = "../../../substrate/primitives/consensus/babe" }
sp-authority-discovery = { version = "26.0.0", path = "../../../substrate/primitives/authority-discovery" }
sp-state-machine = { version = "0.35.0", path = "../../../substrate/primitives/state-machine" }
sp-storage = { version = "19.0.0", path = "../../../substrate/primitives/storage" }
sp-runtime = { version = "31.0.0", path = "../../../substrate/primitives/runtime" }
sp-version = { version = "29.0.0", path = "../../../substrate/primitives/version" }
sc-client-api = { version = "28.0.0", path = "../../../substrate/client/api" }
sc-rpc-api = { version = "0.33.0", path = "../../../substrate/client/rpc-api" }
sc-service = { version = "0.35.0", path = "../../../substrate/client/service" }

tokio = { version = "1.32.0", features = ["sync"] }
tokio-util = { version = "0.7.8", features = ["compat"] }

futures = "0.3.28"
futures-timer = "3.0.2"
parity-scale-codec = "3.6.4"
jsonrpsee = { version = "0.16.2", features = ["ws-client"] }
tracing = "0.1.37"
async-trait = "0.1.74"
url = "2.4.0"
serde_json = "1.0.111"
serde = "1.0.195"
schnellru = "0.2.1"
smoldot = { version = "0.11.0", default_features = false, features = ["std"] }
smoldot-light = { version = "0.9.0", default_features = false, features = ["std"] }
either = "1.8.1"
thiserror = "1.0.48"
rand = "0.8.5"
pin-project = "1.1.3"
