[package]
name = "sc-consensus-babe-rpc"
version = "0.34.0"
authors.workspace = true
description = "RPC extensions for the BABE consensus algorithm"
edition.workspace = true
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
homepage = "https://substrate.io"
repository.workspace = true
readme = "README.md"

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
jsonrpsee = { version = "0.16.2", features = ["client-core", "macros", "server"] }
futures = "0.3.21"
serde = { version = "1.0.195", features = ["derive"] }
thiserror = "1.0"
sc-consensus-babe = { version = "0.34.0", path = ".." }
sc-consensus-epochs = { version = "0.33.0", path = "../../epochs" }
sc-rpc-api = { version = "0.33.0", path = "../../../rpc-api" }
sp-api = { version = "26.0.0", path = "../../../../primitives/api" }
sp-application-crypto = { version = "30.0.0", path = "../../../../primitives/application-crypto" }
sp-blockchain = { version = "28.0.0", path = "../../../../primitives/blockchain" }
sp-consensus = { version = "0.32.0", path = "../../../../primitives/consensus/common" }
sp-consensus-babe = { version = "0.32.0", path = "../../../../primitives/consensus/babe" }
sp-core = { version = "28.0.0", path = "../../../../primitives/core" }
sp-keystore = { version = "0.34.0", path = "../../../../primitives/keystore" }
sp-runtime = { version = "31.0.0", path = "../../../../primitives/runtime" }

[dev-dependencies]
serde_json = "1.0.111"
tokio = "1.22.0"
sc-consensus = { path = "../../common" }
sc-keystore = { path = "../../../keystore" }
sc-transaction-pool-api = { path = "../../../transaction-pool/api" }
sp-keyring = { path = "../../../../primitives/keyring" }
substrate-test-runtime-client = { path = "../../../../test-utils/runtime/client" }
