[package]
name = "xcm-simulator"
description = "Test kit to simulate cross-chain message passing and XCM execution"
version = "7.0.0"
authors.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
codec = { package = "parity-scale-codec", version = "3.6.1" }
paste = "1.0.7"
frame-support = { version = "28.0.0", path = "../../../substrate/frame/support" }
sp-io = { version = "30.0.0", path = "../../../substrate/primitives/io" }
sp-std = { version = "14.0.0", path = "../../../substrate/primitives/std" }

xcm = { package = "staging-xcm", path = "..", version = "7.0.0" }
xcm-executor = { package = "staging-xcm-executor", path = "../xcm-executor", version = "7.0.3" }
xcm-builder = { package = "staging-xcm-builder", path = "../xcm-builder", version = "7.0.3" }
polkadot-core-primitives = { version = "7.0.0", path = "../../core-primitives" }
polkadot-parachain-primitives = { version = "6.0.0", path = "../../parachain" }
polkadot-runtime-parachains = { version = "7.0.0", path = "../../runtime/parachains" }
