[package]
name = "pallet-asset-conversion-tx-payment"
version = "10.0.0"
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
homepage = "https://substrate.io"
repository.workspace = true
description = "Pallet to manage transaction payments in assets by converting them to native assets."
readme = "README.md"

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
# Substrate dependencies
sp-runtime = { path = "../../../primitives/runtime", default-features = false, version = "31.0.0" }
sp-std = { path = "../../../primitives/std", default-features = false, version = "14.0.0" }
frame-support = { path = "../../support", default-features = false, version = "28.0.0" }
frame-system = { path = "../../system", default-features = false, version = "28.0.0" }
pallet-asset-conversion = { path = "../../asset-conversion", default-features = false, version = "10.0.0" }
pallet-transaction-payment = { path = "..", default-features = false, version = "28.0.0" }
codec = { package = "parity-scale-codec", version = "3.2.2", default-features = false, features = ["derive"] }
scale-info = { version = "2.10.0", default-features = false, features = ["derive"] }

[dev-dependencies]
sp-core = { path = "../../../primitives/core", default-features = false }
sp-io = { path = "../../../primitives/io", default-features = false }
sp-storage = { path = "../../../primitives/storage", default-features = false }
pallet-assets = { path = "../../assets" }
pallet-balances = { path = "../../balances" }

[features]
default = ["std"]
std = [
	"codec/std",
	"frame-support/std",
	"frame-system/std",
	"pallet-asset-conversion/std",
	"pallet-transaction-payment/std",
	"scale-info/std",
	"sp-runtime/std",
	"sp-std/std",
]
try-runtime = [
	"frame-support/try-runtime",
	"frame-system/try-runtime",
	"pallet-asset-conversion/try-runtime",
	"pallet-transaction-payment/try-runtime",
	"sp-runtime/try-runtime",
]
