[package]
name = "cumulus-client-parachain-inherent"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
description = "Inherent that needs to be present in every parachain block. Contains messages and a relay chain storage-proof."
license = "Apache-2.0"

[dependencies]
async-trait = "0.1.73"
codec = { package = "parity-scale-codec", version = "3.0.0", features = ["derive"] }
scale-info = { version = "2.10.0", features = ["derive"] }
tracing = { version = "0.1.37" }
sc-client-api = { version = "28.0.0", path = "../../../substrate/client/api" }
sp-api = { version = "26.0.0", path = "../../../substrate/primitives/api" }
sp-core = { version = "28.0.0", path = "../../../substrate/primitives/core" }
sp-inherents = { version = "26.0.0", path = "../../../substrate/primitives/inherents" }
sp-runtime = { version = "31.0.0", path = "../../../substrate/primitives/runtime" }
sp-state-machine = { version = "0.35.0", path = "../../../substrate/primitives/state-machine" }
sp-std = { version = "14.0.0", path = "../../../substrate/primitives/std" }
sp-storage = { version = "19.0.0", path = "../../../substrate/primitives/storage" }
sp-trie = { version = "29.0.0", path = "../../../substrate/primitives/trie" }
cumulus-primitives-core = { version = "0.7.0", path = "../../primitives/core" }
cumulus-primitives-parachain-inherent = { version = "0.7.0", path = "../../primitives/parachain-inherent" }
cumulus-relay-chain-interface = { version = "0.7.0", path = "../relay-chain-interface" }
cumulus-test-relay-sproof-builder = { version = "0.7.0", path = "../../test/relay-sproof-builder" }
