[package]
name = "xcm-executor-integration-tests"
description = "Integration tests for the XCM Executor"
authors.workspace = true
edition.workspace = true
license.workspace = true
version = "0.1.0"
publish = false

[lints]
workspace = true

[dependencies]
codec = { package = "parity-scale-codec", version = "3.6.1" }
frame-support = { path = "../../../../substrate/frame/support", default-features = false, version = "28.0.0" }
frame-system = { version = "28.0.0", path = "../../../../substrate/frame/system" }
futures = "0.3.21"
pallet-transaction-payment = { version = "28.0.0", path = "../../../../substrate/frame/transaction-payment" }
pallet-xcm = { version = "7.0.0", path = "../../pallet-xcm" }
polkadot-test-client = { version = "0.1.0", path = "../../../node/test/client" }
polkadot-test-runtime = { version = "0.1.0", path = "../../../runtime/test-runtime" }
polkadot-test-service = { version = "0.1.0", path = "../../../node/test/service" }
sp-consensus = { version = "0.32.0", path = "../../../../substrate/primitives/consensus/common" }
sp-keyring = { version = "31.0.0", path = "../../../../substrate/primitives/keyring" }
sp-runtime = { path = "../../../../substrate/primitives/runtime", default-features = false, version = "31.0.0" }
sp-state-machine = { version = "0.35.0", path = "../../../../substrate/primitives/state-machine" }
xcm = { package = "staging-xcm", path = "../..", default-features = false, version = "7.0.0" }
xcm-executor = { package = "staging-xcm-executor", path = "..", version = "7.0.3" }
sp-tracing = { version = "16.0.0", path = "../../../../substrate/primitives/tracing" }

[features]
default = ["std"]
std = ["frame-support/std", "sp-runtime/std", "xcm/std"]
