[package]
name = "polkadot-node-core-pvf-execute-worker"
description = "Polkadot crate that contains the logic for executing PVFs. Used by the polkadot-execute-worker binary."
version = "7.0.0"
authors.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
cpu-time = "1.0.0"
gum = { package = "tracing-gum", path = "../../../gum", version = "7.0.0" }
os_pipe = "1.1.4"
nix = { version = "0.27.1", features = ["process", "resource"] }
libc = "0.2.139"

parity-scale-codec = { version = "3.6.1", default-features = false, features = ["derive"] }
polkadot-node-core-pvf-common = { version = "7.0.0", path = "../common" }
polkadot-parachain-primitives = { version = "6.0.0", path = "../../../../parachain" }
polkadot-primitives = { version = "7.0.0", path = "../../../../primitives" }

[features]
builder = []
