[package]
name = "polkadot-node-primitives"
description = "Primitives types for the Node-side"
version = "7.0.0"
authors.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
bounded-vec = "0.7"
futures = "0.3.21"
polkadot-primitives = { version = "7.0.0", path = "../../primitives" }
parity-scale-codec = { version = "3.6.1", default-features = false, features = ["derive"] }
sp-core = { version = "28.0.0", path = "../../../substrate/primitives/core" }
sp-application-crypto = { version = "30.0.0", path = "../../../substrate/primitives/application-crypto" }
sp-consensus-babe = { version = "0.32.0", path = "../../../substrate/primitives/consensus/babe" }
sp-keystore = { version = "0.34.0", path = "../../../substrate/primitives/keystore" }
sp-maybe-compressed-blob = { version = "11.0.0", path = "../../../substrate/primitives/maybe-compressed-blob" }
sp-runtime = { version = "31.0.0", path = "../../../substrate/primitives/runtime" }
polkadot-parachain-primitives = { path = "../../parachain", default-features = false, version = "6.0.0" }
schnorrkel = "0.11.4"
thiserror = "1.0.48"
bitvec = { version = "1.0.0", default-features = false, features = ["alloc"] }
serde = { version = "1.0.195", features = ["derive"] }

[target.'cfg(not(target_os = "unknown"))'.dependencies]
zstd = { version = "0.12.4", default-features = false }

[dev-dependencies]
polkadot-erasure-coding = { path = "../../erasure-coding" }
