[package]
name = "minimal-runtime"
version = "0.1.0"
authors.workspace = true
description = "A minimal Substrate example runtime"
edition.workspace = true
repository.workspace = true
license.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
parity-scale-codec = { version = "3.0.0", default-features = false }
scale-info = { version = "2.6.0", default-features = false }

# this is a frame-based runtime, thus importing `frame` with runtime feature enabled.
frame = { path = "../../../frame", default-features = false, features = ["experimental", "runtime"], version = "0.1.0" }
frame-support = { path = "../../../frame/support", default-features = false, version = "28.0.0" }

# pallets that we want to use
pallet-balances = { path = "../../../frame/balances", default-features = false, version = "28.0.0" }
pallet-sudo = { path = "../../../frame/sudo", default-features = false, version = "28.0.0" }
pallet-timestamp = { path = "../../../frame/timestamp", default-features = false, version = "27.0.0" }
pallet-transaction-payment = { path = "../../../frame/transaction-payment", default-features = false, version = "28.0.0" }
pallet-transaction-payment-rpc-runtime-api = { path = "../../../frame/transaction-payment/rpc/runtime-api", default-features = false, version = "28.0.0" }

# genesis builder that allows us to interacto with runtime genesis config
sp-genesis-builder = { path = "../../../primitives/genesis-builder", default-features = false, version = "0.7.0" }


[build-dependencies]
substrate-wasm-builder = { path = "../../../utils/wasm-builder", optional = true, version = "17.0.0" }

[features]
default = ["std"]
std = [
	"frame-support/std",
	"frame/std",
	"pallet-balances/std",
	"pallet-sudo/std",
	"pallet-timestamp/std",
	"pallet-transaction-payment-rpc-runtime-api/std",
	"pallet-transaction-payment/std",
	"parity-scale-codec/std",
	"scale-info/std",
	"sp-genesis-builder/std",
	"substrate-wasm-builder",
]
