[package]
name = "pallet-root-offences"
version = "25.0.0"
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
homepage = "https://substrate.io"
repository.workspace = true
description = "FRAME root offences pallet"
readme = "README.md"

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "3.6.1", default-features = false, features = ["derive"] }
scale-info = { version = "2.10.0", default-features = false, features = ["derive"] }

pallet-session = { path = "../session", default-features = false, features = ["historical"], version = "28.0.0" }
pallet-staking = { path = "../staking", default-features = false, version = "28.0.1" }

frame-support = { path = "../support", default-features = false, version = "28.0.0" }
frame-system = { path = "../system", default-features = false, version = "28.0.0" }
sp-runtime = { version = "31.0.0", path = "../../primitives/runtime" }
sp-staking = { path = "../../primitives/staking", default-features = false, version = "26.0.0" }

[dev-dependencies]
pallet-balances = { path = "../balances" }
pallet-timestamp = { path = "../timestamp" }
pallet-staking-reward-curve = { path = "../staking/reward-curve" }
sp-core = { path = "../../primitives/core" }
sp-io = { path = "../../primitives/io", default-features = false }
sp-std = { path = "../../primitives/std", default-features = false }
frame-election-provider-support = { path = "../election-provider-support" }

[features]
runtime-benchmarks = [
	"frame-support/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
	"pallet-staking/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
	"sp-staking/runtime-benchmarks",
]
try-runtime = [
	"frame-support/try-runtime",
	"frame-system/try-runtime",
	"pallet-session/try-runtime",
	"pallet-staking/try-runtime",
	"sp-runtime/try-runtime",
]
default = ["std"]
std = [
	"codec/std",
	"frame-support/std",
	"frame-system/std",
	"pallet-session/std",
	"pallet-staking/std",
	"scale-info/std",
	"sp-runtime/std",
	"sp-staking/std",
]
