[package]
name = "pallet-transaction-payment-rpc-runtime-api"
version = "28.0.0"
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
homepage = "https://substrate.io"
repository.workspace = true
description = "RPC runtime API for transaction payment FRAME pallet"
readme = "README.md"

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "3.6.1", default-features = false, features = ["derive"] }
pallet-transaction-payment = { path = "../..", default-features = false, version = "28.0.0" }
sp-api = { path = "../../../../primitives/api", default-features = false, version = "26.0.0" }
sp-runtime = { path = "../../../../primitives/runtime", default-features = false, version = "31.0.0" }
sp-weights = { path = "../../../../primitives/weights", default-features = false, version = "27.0.0" }

[features]
default = ["std"]
std = [
	"codec/std",
	"pallet-transaction-payment/std",
	"sp-api/std",
	"sp-runtime/std",
	"sp-weights/std",
]
