[package]
authors.workspace = true
name = "cumulus-relay-chain-inprocess-interface"
version = "0.7.0"
edition.workspace = true
description = "Implementation of the RelayChainInterface trait for Polkadot full-nodes."
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"

[lints]
workspace = true

[dependencies]
async-trait = "0.1.74"
futures = "0.3.28"
futures-timer = "3.0.2"
sc-cli = { version = "0.36.0", path = "../../../substrate/client/cli" }
sc-client-api = { version = "28.0.0", path = "../../../substrate/client/api" }
sc-telemetry = { version = "15.0.0", path = "../../../substrate/client/telemetry" }
sc-tracing = { version = "28.0.0", path = "../../../substrate/client/tracing" }
sc-sysinfo = { version = "27.0.0", path = "../../../substrate/client/sysinfo" }
sp-api = { version = "26.0.0", path = "../../../substrate/primitives/api" }
sp-consensus = { version = "0.32.0", path = "../../../substrate/primitives/consensus/common" }
sp-core = { version = "28.0.0", path = "../../../substrate/primitives/core" }
sp-runtime = { version = "31.0.0", path = "../../../substrate/primitives/runtime" }
sp-state-machine = { version = "0.35.0", path = "../../../substrate/primitives/state-machine" }

# Polkadot
polkadot-cli = { path = "../../../polkadot/cli", default-features = false, features = ["cli"], version = "7.0.0" }
polkadot-service = { version = "7.0.0", path = "../../../polkadot/node/service" }
cumulus-primitives-core = { version = "0.7.0", path = "../../primitives/core" }
cumulus-relay-chain-interface = { version = "0.7.0", path = "../relay-chain-interface" }

[dev-dependencies]
sp-keyring = { path = "../../../substrate/primitives/keyring" }
polkadot-primitives = { path = "../../../polkadot/primitives" }
polkadot-test-client = { path = "../../../polkadot/node/test/client" }
metered = { package = "prioritized-metered-channel", version = "0.5.1", default-features = false, features = ["futures_channel"] }
cumulus-test-service = { path = "../../test/service" }
