[package]
name = "minimal-node"
version = "0.1.0"
description = "A fresh FRAME-based Substrate node, ready for hacking."
authors = ["Substrate DevHub <https://github.com/substrate-developer-hub>"]
homepage = "https://substrate.io/"
edition = "2021"
license = "MIT-0"
publish = false
repository = "https://github.com/substrate-developer-hub/substrate-node-template/"
build = "build.rs"

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[[bin]]
name = "minimal-node"

[dependencies]
clap = { version = "4.4.14", features = ["derive"] }
futures = { version = "0.3.21", features = ["thread-pool"] }
futures-timer = "3.0.1"
jsonrpsee = { version = "0.16.2", features = ["server"] }
serde_json = "1.0.111"
sc-cli = { version = "0.36.0", path = "../../../client/cli" }
sc-executor = { version = "0.32.0", path = "../../../client/executor" }
sc-network = { version = "0.34.0", path = "../../../client/network" }
sc-service = { version = "0.35.0", path = "../../../client/service" }
sc-telemetry = { version = "15.0.0", path = "../../../client/telemetry" }
sc-transaction-pool = { version = "28.0.0", path = "../../../client/transaction-pool" }
sc-transaction-pool-api = { version = "28.0.0", path = "../../../client/transaction-pool/api" }
sc-consensus = { version = "0.33.0", path = "../../../client/consensus/common" }
sc-consensus-manual-seal = { version = "0.35.0", path = "../../../client/consensus/manual-seal" }
sc-rpc-api = { version = "0.33.0", path = "../../../client/rpc-api" }
sc-basic-authorship = { version = "0.34.0", path = "../../../client/basic-authorship" }
sc-offchain = { version = "29.0.0", path = "../../../client/offchain" }
sc-client-api = { version = "28.0.0", path = "../../../client/api" }
sp-timestamp = { version = "26.0.0", path = "../../../primitives/timestamp" }
sp-keyring = { version = "31.0.0", path = "../../../primitives/keyring" }
sp-api = { version = "26.0.0", path = "../../../primitives/api" }
sp-blockchain = { version = "28.0.0", path = "../../../primitives/blockchain" }
sp-block-builder = { version = "26.0.0", path = "../../../primitives/block-builder" }
sp-io = { version = "30.0.0", path = "../../../primitives/io" }
sp-runtime = { version = "31.0.0", path = "../../../primitives/runtime" }
substrate-frame-rpc-system = { version = "28.0.0", path = "../../../utils/frame/rpc/system" }

frame = { path = "../../../frame", features = ["experimental", "runtime"], version = "0.1.0" }
runtime = { package = "minimal-runtime", path = "../runtime", version = "0.1.0" }

[build-dependencies]
substrate-build-script-utils = { version = "11.0.0", path = "../../../utils/build-script-utils" }

[features]
default = []
