[package]
authors.workspace = true
edition.workspace = true
name = "cumulus-pallet-xcm"
version = "0.7.0"
license = "Apache-2.0"
description = "Pallet for stuff specific to parachains' usage of XCM"

[lints]
workspace = true

[dependencies]
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive"] }
scale-info = { version = "2.10.0", default-features = false, features = ["derive"] }

sp-std = { path = "../../../substrate/primitives/std", default-features = false, version = "14.0.0" }
sp-io = { path = "../../../substrate/primitives/io", default-features = false, version = "30.0.0" }
sp-runtime = { path = "../../../substrate/primitives/runtime", default-features = false, version = "31.0.0" }
frame-support = { path = "../../../substrate/frame/support", default-features = false, version = "28.0.0" }
frame-system = { path = "../../../substrate/frame/system", default-features = false, version = "28.0.0" }

xcm = { package = "staging-xcm", path = "../../../polkadot/xcm", default-features = false, version = "7.0.0" }

cumulus-primitives-core = { path = "../../primitives/core", default-features = false, version = "0.7.0" }

[features]
default = ["std"]
std = [
	"codec/std",
	"cumulus-primitives-core/std",
	"frame-support/std",
	"frame-system/std",
	"scale-info/std",
	"sp-io/std",
	"sp-runtime/std",
	"sp-std/std",
	"xcm/std",
]
try-runtime = [
	"frame-support/try-runtime",
	"frame-system/try-runtime",
	"sp-runtime/try-runtime",
]
