[package]
name = "pallet-nomination-pools-fuzzer"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
homepage = "https://substrate.io"
repository.workspace = true
description = "Fuzzer for fixed point arithmetic primitives."
documentation = "https://docs.rs/sp-arithmetic-fuzzer"
publish = false

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
honggfuzz = "0.5.54"

pallet-nomination-pools = { path = "..", features = ["fuzzing"], version = "25.0.3" }
frame-system = { version = "28.0.0", path = "../../system" }
frame-support = { version = "28.0.0", path = "../../support" }
sp-runtime = { version = "31.0.0", path = "../../../primitives/runtime" }
sp-io = { version = "30.0.0", path = "../../../primitives/io" }
sp-tracing = { version = "16.0.0", path = "../../../primitives/tracing" }

rand = { version = "0.8.5", features = ["small_rng"] }
log = "0.4.17"

[[bin]]
name = "call"
path = "src/call.rs"
