[package]
name = "emulated-integration-tests-common"
version = "3.0.0"
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
description = "Common resources for integration testing with xcm-emulator"

[lints]
workspace = true

[dependencies]
codec = { package = "parity-scale-codec", version = "3.4.0", default-features = false }
paste = "1.0.14"
serde_json = "1.0.111"

# Substrate
grandpa = { package = "sc-consensus-grandpa", path = "../../../../../substrate/client/consensus/grandpa", version = "0.19.0" }
sp-authority-discovery = { path = "../../../../../substrate/primitives/authority-discovery", default-features = false, version = "26.0.0" }
sp-runtime = { path = "../../../../../substrate/primitives/runtime", default-features = false, version = "31.0.0" }
frame-support = { path = "../../../../../substrate/frame/support", default-features = false, version = "28.0.0" }
sp-core = { path = "../../../../../substrate/primitives/core", default-features = false, version = "28.0.0" }
sp-consensus-babe = { path = "../../../../../substrate/primitives/consensus/babe", default-features = false, version = "0.32.0" }
pallet-assets = { path = "../../../../../substrate/frame/assets", default-features = false, version = "29.0.0" }
pallet-balances = { path = "../../../../../substrate/frame/balances", default-features = false, version = "28.0.0" }
pallet-message-queue = { path = "../../../../../substrate/frame/message-queue", default-features = false, version = "31.0.0" }
pallet-im-online = { path = "../../../../../substrate/frame/im-online", default-features = false, version = "27.0.0" }
beefy-primitives = { package = "sp-consensus-beefy", path = "../../../../../substrate/primitives/consensus/beefy", version = "13.0.0" }

# Polkadot
polkadot-service = { path = "../../../../../polkadot/node/service", default-features = false, features = ["full-node"], version = "7.0.0" }
polkadot-primitives = { path = "../../../../../polkadot/primitives", default-features = false, version = "7.0.0" }
polkadot-runtime-parachains = { version = "7.0.0", path = "../../../../../polkadot/runtime/parachains" }
xcm = { package = "staging-xcm", path = "../../../../../polkadot/xcm", default-features = false, version = "7.0.0" }
pallet-xcm = { path = "../../../../../polkadot/xcm/pallet-xcm", default-features = false, version = "7.0.0" }
parachains-common = { version = "7.0.0", path = "../../../common" }
cumulus-primitives-core = { version = "0.7.0", path = "../../../../primitives/core" }
xcm-emulator = { path = "../../../../xcm/xcm-emulator", default-features = false, version = "0.5.0" }
cumulus-pallet-xcmp-queue = { path = "../../../../pallets/xcmp-queue", default-features = false, version = "0.7.0" }
cumulus-pallet-parachain-system = { version = "0.7.0", path = "../../../../pallets/parachain-system" }
asset-test-utils = { version = "7.0.1", path = "../../../runtimes/assets/test-utils" }
bp-messages = { version = "0.7.0", path = "../../../../../bridges/primitives/messages" }
pallet-bridge-messages = { version = "0.7.0", path = "../../../../../bridges/modules/messages" }
bridge-runtime-common = { version = "0.7.0", path = "../../../../../bridges/bin/runtime-common" }
