[package]
name = "sc-statement-store"
version = "10.0.0"
authors.workspace = true
edition.workspace = true
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
homepage = "https://substrate.io"
repository.workspace = true
description = "Substrate statement store."
readme = "README.md"

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
log = "0.4.17"
parking_lot = "0.12.1"
parity-db = "0.4.12"
tokio = { version = "1.22.0", features = ["time"] }
sp-statement-store = { version = "10.0.0", path = "../../primitives/statement-store" }
prometheus-endpoint = { package = "substrate-prometheus-endpoint", path = "../../utils/prometheus", version = "0.17.0" }
sp-api = { version = "26.0.0", path = "../../primitives/api" }
sp-blockchain = { version = "28.0.0", path = "../../primitives/blockchain" }
sp-core = { version = "28.0.0", path = "../../primitives/core" }
sp-runtime = { version = "31.0.0", path = "../../primitives/runtime" }
sc-client-api = { version = "28.0.0", path = "../api" }
sc-keystore = { version = "25.0.0", path = "../keystore" }

[dev-dependencies]
tempfile = "3.1.0"
env_logger = "0.9"
