[package]
authors.workspace = true
description = "Simple pallet to select collators for a parachain."
edition.workspace = true
homepage = "https://substrate.io"
license = "Apache-2.0"
name = "pallet-collator-selection"
readme = "README.md"
repository.workspace = true
version = "9.0.2"

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
log = { version = "0.4.20", default-features = false }
codec = { default-features = false, features = ["derive"], package = "parity-scale-codec", version = "3.0.0" }
rand = { version = "0.8.5", features = ["std_rng"], default-features = false }
scale-info = { version = "2.10.0", default-features = false, features = ["derive"] }

sp-std = { path = "../../../substrate/primitives/std", default-features = false, version = "14.0.0" }
sp-runtime = { path = "../../../substrate/primitives/runtime", default-features = false, version = "31.0.0" }
sp-staking = { path = "../../../substrate/primitives/staking", default-features = false, version = "26.0.0" }
frame-support = { path = "../../../substrate/frame/support", default-features = false, version = "28.0.0" }
frame-system = { path = "../../../substrate/frame/system", default-features = false, version = "28.0.0" }
pallet-authorship = { path = "../../../substrate/frame/authorship", default-features = false, version = "28.0.0" }
pallet-balances = { path = "../../../substrate/frame/balances", default-features = false, version = "28.0.0" }
pallet-session = { path = "../../../substrate/frame/session", default-features = false, version = "28.0.0" }

frame-benchmarking = { path = "../../../substrate/frame/benchmarking", default-features = false, optional = true, version = "28.0.0" }

[dev-dependencies]
sp-core = { path = "../../../substrate/primitives/core" }
sp-io = { path = "../../../substrate/primitives/io" }
sp-tracing = { path = "../../../substrate/primitives/tracing" }
sp-runtime = { path = "../../../substrate/primitives/runtime" }
pallet-timestamp = { path = "../../../substrate/frame/timestamp" }
sp-consensus-aura = { path = "../../../substrate/primitives/consensus/aura" }
pallet-aura = { path = "../../../substrate/frame/aura" }

[features]
default = ["std"]
runtime-benchmarks = [
	"frame-benchmarking/runtime-benchmarks",
	"frame-support/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
	"sp-staking/runtime-benchmarks",
]
std = [
	"codec/std",
	"frame-benchmarking/std",
	"frame-support/std",
	"frame-system/std",
	"log/std",
	"pallet-authorship/std",
	"pallet-balances/std",
	"pallet-session/std",
	"rand/std",
	"scale-info/std",
	"sp-runtime/std",
	"sp-staking/std",
	"sp-std/std",
]

try-runtime = [
	"frame-support/try-runtime",
	"frame-system/try-runtime",
	"pallet-authorship/try-runtime",
	"pallet-session/try-runtime",
	"sp-runtime/try-runtime",
]

experimental = []
