[package]
name = "sc-cli"
version = "0.36.0"
authors.workspace = true
description = "Substrate CLI interface."
edition.workspace = true
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
homepage = "https://substrate.io"
repository.workspace = true
readme = "README.md"

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
array-bytes = "6.1"
chrono = "0.4.31"
clap = { version = "4.4.14", features = ["derive", "string", "wrap_help"] }
fdlimit = "0.3.0"
futures = "0.3.21"
itertools = "0.10.3"
libp2p-identity = { version = "0.1.3", features = ["ed25519", "peerid"] }
log = "0.4.17"
names = { version = "0.14.0", default-features = false }
parity-scale-codec = "3.6.1"
rand = "0.8.5"
regex = "1.6.0"
rpassword = "7.0.0"
serde = "1.0.195"
serde_json = "1.0.111"
thiserror = "1.0.48"
bip39 = "2.0.0"
tokio = { version = "1.22.0", features = ["parking_lot", "rt-multi-thread", "signal"] }
sc-client-api = { version = "28.0.0", path = "../api" }
sc-client-db = { path = "../db", default-features = false, version = "0.35.0" }
sc-keystore = { version = "25.0.0", path = "../keystore" }
sc-mixnet = { version = "0.4.0", path = "../mixnet" }
sc-network = { version = "0.34.0", path = "../network" }
sc-service = { path = "../service", default-features = false, version = "0.35.0" }
sc-telemetry = { version = "15.0.0", path = "../telemetry" }
sc-tracing = { version = "28.0.0", path = "../tracing" }
sc-utils = { version = "14.0.0", path = "../utils" }
sp-blockchain = { version = "28.0.0", path = "../../primitives/blockchain" }
sp-core = { version = "28.0.0", path = "../../primitives/core" }
sp-keyring = { version = "31.0.0", path = "../../primitives/keyring" }
sp-keystore = { version = "0.34.0", path = "../../primitives/keystore" }
sp-panic-handler = { version = "13.0.0", path = "../../primitives/panic-handler" }
sp-runtime = { version = "31.0.0", path = "../../primitives/runtime" }
sp-version = { version = "29.0.0", path = "../../primitives/version" }

[dev-dependencies]
tempfile = "3.1.0"
futures-timer = "3.0.1"
sp-tracing = { path = "../../primitives/tracing" }

[features]
default = ["rocksdb"]
rocksdb = ["sc-client-db/rocksdb"]
