[package]
name = "cumulus-client-collator"
version = "0.7.0"
authors.workspace = true
edition.workspace = true
description = "Common node-side functionality and glue code to collate parachain blocks."
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"

[lints]
workspace = true

[dependencies]
parking_lot = "0.12.1"
codec = { package = "parity-scale-codec", version = "3.0.0", features = ["derive"] }
futures = "0.3.21"
tracing = "0.1.25"
sc-client-api = { version = "28.0.0", path = "../../../substrate/client/api" }
sp-consensus = { version = "0.32.0", path = "../../../substrate/primitives/consensus/common" }
sp-api = { version = "26.0.0", path = "../../../substrate/primitives/api" }
sp-core = { version = "28.0.0", path = "../../../substrate/primitives/core" }
sp-runtime = { version = "31.0.0", path = "../../../substrate/primitives/runtime" }
polkadot-node-primitives = { version = "7.0.0", path = "../../../polkadot/node/primitives" }
polkadot-node-subsystem = { version = "7.0.0", path = "../../../polkadot/node/subsystem" }
polkadot-overseer = { version = "7.0.0", path = "../../../polkadot/node/overseer" }
polkadot-primitives = { version = "7.0.0", path = "../../../polkadot/primitives" }
cumulus-client-consensus-common = { version = "0.7.0", path = "../consensus/common" }
cumulus-client-network = { version = "0.7.0", path = "../network" }
cumulus-primitives-core = { version = "0.7.0", path = "../../primitives/core" }

[dev-dependencies]
async-trait = "0.1.74"
sp-maybe-compressed-blob = { path = "../../../substrate/primitives/maybe-compressed-blob" }
sp-state-machine = { path = "../../../substrate/primitives/state-machine" }
sp-tracing = { path = "../../../substrate/primitives/tracing" }
polkadot-node-subsystem-test-helpers = { path = "../../../polkadot/node/subsystem-test-helpers" }
cumulus-test-client = { path = "../../test/client" }
cumulus-test-runtime = { path = "../../test/runtime" }
cumulus-test-relay-sproof-builder = { path = "../../test/relay-sproof-builder" }
