[package]
name = "cumulus-client-pov-recovery"
version = "0.7.0"
authors.workspace = true
description = "Cumulus-specific networking protocol"
edition.workspace = true
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"

[lints]
workspace = true

[dependencies]
codec = { package = "parity-scale-codec", version = "3.0.0", features = ["derive"] }
futures = "0.3.28"
futures-timer = "3.0.2"
rand = "0.8.5"
tracing = "0.1.37"
sc-client-api = { version = "28.0.0", path = "../../../substrate/client/api" }
sc-consensus = { version = "0.33.0", path = "../../../substrate/client/consensus/common" }
sp-consensus = { version = "0.32.0", path = "../../../substrate/primitives/consensus/common" }
sp-maybe-compressed-blob = { version = "11.0.0", path = "../../../substrate/primitives/maybe-compressed-blob" }
sp-runtime = { version = "31.0.0", path = "../../../substrate/primitives/runtime" }
polkadot-node-primitives = { version = "7.0.0", path = "../../../polkadot/node/primitives" }
polkadot-node-subsystem = { version = "7.0.0", path = "../../../polkadot/node/subsystem" }
polkadot-overseer = { version = "7.0.0", path = "../../../polkadot/node/overseer" }
polkadot-primitives = { version = "7.0.0", path = "../../../polkadot/primitives" }
cumulus-primitives-core = { version = "0.7.0", path = "../../primitives/core" }
cumulus-relay-chain-interface = { version = "0.7.0", path = "../relay-chain-interface" }
async-trait = "0.1.74"

[dev-dependencies]
tokio = { version = "1.32.0", features = ["macros"] }
portpicker = "0.1.1"
cumulus-test-service = { path = "../../test/service" }
sc-cli = { path = "../../../substrate/client/cli" }
sc-client-api = { path = "../../../substrate/client/api" }
substrate-test-utils = { path = "../../../substrate/test-utils" }
