[package]
name = "assets-common"
version = "0.7.0"
authors.workspace = true
edition.workspace = true
description = "Assets common utilities"
license = "Apache-2.0"

[lints]
workspace = true

[dependencies]
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive"] }
scale-info = { version = "2.10.0", default-features = false, features = ["derive"] }
log = { version = "0.4.20", default-features = false }
impl-trait-for-tuples = "0.2.2"

# Substrate
frame-support = { path = "../../../../../substrate/frame/support", default-features = false, version = "28.0.0" }
sp-api = { path = "../../../../../substrate/primitives/api", default-features = false, version = "26.0.0" }
sp-std = { path = "../../../../../substrate/primitives/std", default-features = false, version = "14.0.0" }
sp-runtime = { path = "../../../../../substrate/primitives/runtime", default-features = false, version = "31.0.0" }
pallet-asset-conversion = { path = "../../../../../substrate/frame/asset-conversion", default-features = false, version = "10.0.0" }
pallet-asset-tx-payment = { path = "../../../../../substrate/frame/transaction-payment/asset-tx-payment", default-features = false, version = "28.0.0" }

# Polkadot
pallet-xcm = { path = "../../../../../polkadot/xcm/pallet-xcm", default-features = false, version = "7.0.0" }
xcm = { package = "staging-xcm", path = "../../../../../polkadot/xcm", default-features = false, version = "7.0.0" }
xcm-builder = { package = "staging-xcm-builder", path = "../../../../../polkadot/xcm/xcm-builder", default-features = false, version = "7.0.3" }
xcm-executor = { package = "staging-xcm-executor", path = "../../../../../polkadot/xcm/xcm-executor", default-features = false, version = "7.0.3" }

# Cumulus
parachains-common = { path = "../../../common", default-features = false, version = "7.0.0" }
cumulus-primitives-core = { path = "../../../../primitives/core", default-features = false, version = "0.7.0" }

[build-dependencies]
substrate-wasm-builder = { version = "17.0.0", path = "../../../../../substrate/utils/wasm-builder" }

[features]
default = ["std"]
std = [
	"codec/std",
	"cumulus-primitives-core/std",
	"frame-support/std",
	"log/std",
	"pallet-asset-conversion/std",
	"pallet-asset-tx-payment/std",
	"pallet-xcm/std",
	"parachains-common/std",
	"scale-info/std",
	"sp-api/std",
	"sp-runtime/std",
	"sp-std/std",
	"xcm-builder/std",
	"xcm-executor/std",
	"xcm/std",
]

runtime-benchmarks = [
	"cumulus-primitives-core/runtime-benchmarks",
	"frame-support/runtime-benchmarks",
	"pallet-asset-conversion/runtime-benchmarks",
	"pallet-asset-tx-payment/runtime-benchmarks",
	"pallet-xcm/runtime-benchmarks",
	"parachains-common/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
	"xcm-builder/runtime-benchmarks",
	"xcm-executor/runtime-benchmarks",
]
