[package]
name = "snowbridge-core"
description = "Snowbridge Core"
version = "0.1.0"
authors = ["Snowfork <contact@snowfork.com>"]
edition = "2021"
license = "Apache-2.0"
publish = false

[dependencies]
serde = { version = "1.0.195", optional = true, features = ["alloc", "derive"], default-features = false }
codec = { package = "parity-scale-codec", version = "3.6.1", default-features = false }
scale-info = { version = "2.9.0", default-features = false, features = ["derive"] }
hex-literal = { version = "0.4.1" }

polkadot-parachain-primitives = { path = "../../../../../polkadot/parachain", default-features = false, version = "6.0.0" }
xcm = { package = "staging-xcm", path = "../../../../../polkadot/xcm", default-features = false, version = "7.0.0" }
xcm-builder = { package = "staging-xcm-builder", path = "../../../../../polkadot/xcm/xcm-builder", default-features = false, version = "7.0.3" }

frame-support = { path = "../../../../../substrate/frame/support", default-features = false, version = "28.0.0" }
frame-system = { path = "../../../../../substrate/frame/system", default-features = false, version = "28.0.0" }
sp-runtime = { path = "../../../../../substrate/primitives/runtime", default-features = false, version = "31.0.0" }
sp-std = { path = "../../../../../substrate/primitives/std", default-features = false, version = "14.0.0" }
sp-io = { path = "../../../../../substrate/primitives/io", default-features = false, version = "30.0.0" }
sp-core = { path = "../../../../../substrate/primitives/core", default-features = false, version = "28.0.0" }
sp-arithmetic = { path = "../../../../../substrate/primitives/arithmetic", default-features = false, version = "23.0.0" }

snowbridge-beacon-primitives = { path = "../beacon", default-features = false, version = "0.1.0" }

ethabi = { git = "https://github.com/Snowfork/ethabi-decode.git", package = "ethabi-decode", branch = "master", default-features = false }

[dev-dependencies]
hex = { version = "0.4.3" }

[features]
default = ["std"]
std = [
	"codec/std",
	"ethabi/std",
	"frame-support/std",
	"frame-system/std",
	"polkadot-parachain-primitives/std",
	"scale-info/std",
	"serde/std",
	"snowbridge-beacon-primitives/std",
	"sp-arithmetic/std",
	"sp-core/std",
	"sp-io/std",
	"sp-runtime/std",
	"sp-std/std",
	"xcm-builder/std",
	"xcm/std",
]
serde = ["dep:serde", "scale-info/serde"]
runtime-benchmarks = [
	"frame-support/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
	"polkadot-parachain-primitives/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
	"xcm-builder/runtime-benchmarks",
]
