[package]
name = "sc-sysinfo"
version = "27.0.0"
authors.workspace = true
edition.workspace = true
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
homepage = "https://substrate.io"
repository.workspace = true
description = "A crate that provides basic hardware and software telemetry information."
documentation = "https://docs.rs/sc-sysinfo"
readme = "README.md"

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
futures = "0.3.19"
libc = "0.2"
log = "0.4.17"
rand = "0.8.5"
rand_pcg = "0.3.1"
derive_more = "0.99"
regex = "1"
serde = { version = "1.0.195", features = ["derive"] }
serde_json = "1.0.111"
sc-telemetry = { version = "15.0.0", path = "../telemetry" }
sp-core = { version = "28.0.0", path = "../../primitives/core" }
sp-io = { version = "30.0.0", path = "../../primitives/io" }
sp-std = { version = "14.0.0", path = "../../primitives/std" }

[dev-dependencies]
sp-runtime = { path = "../../primitives/runtime" }
