[package]
name = "pallet-nomination-pools-runtime-api"
version = "23.0.0"
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
homepage = "https://substrate.io"
repository.workspace = true
description = "Runtime API for nomination-pools FRAME pallet"
readme = "README.md"

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "3.6.1", default-features = false, features = ["derive"] }
sp-api = { path = "../../../primitives/api", default-features = false, version = "26.0.0" }
sp-std = { path = "../../../primitives/std", default-features = false, version = "14.0.0" }
pallet-nomination-pools = { path = "..", default-features = false, version = "25.0.3" }

[features]
default = ["std"]
std = ["codec/std", "pallet-nomination-pools/std", "sp-api/std", "sp-std/std"]
