[package]
name = "bp-messages"
description = "Primitives of messages module."
version = "0.7.0"
authors.workspace = true
edition.workspace = true
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"

[lints]
workspace = true

[dependencies]
codec = { package = "parity-scale-codec", version = "3.1.5", default-features = false, features = ["bit-vec", "derive"] }
scale-info = { version = "2.10.0", default-features = false, features = ["bit-vec", "derive"] }
serde = { version = "1.0", default-features = false, features = ["alloc", "derive"] }

# Bridge dependencies

bp-runtime = { path = "../runtime", default-features = false, version = "0.7.0" }
bp-header-chain = { path = "../header-chain", default-features = false, version = "0.7.0" }

# Substrate Dependencies

frame-support = { path = "../../../substrate/frame/support", default-features = false, version = "28.0.0" }
sp-core = { path = "../../../substrate/primitives/core", default-features = false, version = "28.0.0" }
sp-std = { path = "../../../substrate/primitives/std", default-features = false, version = "14.0.0" }

[dev-dependencies]
hex = "0.4"
hex-literal = "0.4"

[features]
default = ["std"]
std = [
	"bp-header-chain/std",
	"bp-runtime/std",
	"codec/std",
	"frame-support/std",
	"scale-info/std",
	"serde/std",
	"sp-core/std",
	"sp-std/std",
]
