[package]
name = "pallet-bridge-messages"
description = "Module that allows bridged chains to exchange messages using lane concept."
version = "0.7.0"
authors.workspace = true
edition.workspace = true
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"

[lints]
workspace = true

[dependencies]
codec = { package = "parity-scale-codec", version = "3.1.5", default-features = false }
log = { version = "0.4.20", default-features = false }
num-traits = { version = "0.2", default-features = false }
scale-info = { version = "2.10.0", default-features = false, features = ["derive"] }

# Bridge dependencies

bp-messages = { path = "../../primitives/messages", default-features = false, version = "0.7.0" }
bp-runtime = { path = "../../primitives/runtime", default-features = false, version = "0.7.0" }

# Substrate Dependencies

frame-benchmarking = { path = "../../../substrate/frame/benchmarking", default-features = false, optional = true, version = "28.0.0" }
frame-support = { path = "../../../substrate/frame/support", default-features = false, version = "28.0.0" }
frame-system = { path = "../../../substrate/frame/system", default-features = false, version = "28.0.0" }
sp-runtime = { path = "../../../substrate/primitives/runtime", default-features = false, version = "31.0.0" }
sp-std = { path = "../../../substrate/primitives/std", default-features = false, version = "14.0.0" }

[dev-dependencies]
bp-test-utils = { path = "../../primitives/test-utils" }
pallet-balances = { path = "../../../substrate/frame/balances" }
sp-io = { path = "../../../substrate/primitives/io" }

[features]
default = ["std"]
std = [
	"bp-messages/std",
	"bp-runtime/std",
	"codec/std",
	"frame-benchmarking/std",
	"frame-support/std",
	"frame-system/std",
	"log/std",
	"num-traits/std",
	"scale-info/std",
	"sp-runtime/std",
	"sp-std/std",
]
runtime-benchmarks = [
	"frame-benchmarking/runtime-benchmarks",
	"frame-support/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
]
try-runtime = [
	"frame-support/try-runtime",
	"frame-system/try-runtime",
	"sp-runtime/try-runtime",
]
