[package]
name = "parachains-common"
version = "7.0.0"
authors.workspace = true
edition.workspace = true
description = "Logic which is common to all parachain runtimes"
license = "Apache-2.0"

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "3.0.0", features = ["derive"], default-features = false }
log = { version = "0.4.19", default-features = false }
scale-info = { version = "2.10.0", default-features = false, features = ["derive"] }
num-traits = { version = "0.2", default-features = false }
smallvec = "1.11.0"

# Substrate
frame-support = { path = "../../../substrate/frame/support", default-features = false, version = "28.0.0" }
frame-system = { path = "../../../substrate/frame/system", default-features = false, version = "28.0.0" }
pallet-asset-tx-payment = { path = "../../../substrate/frame/transaction-payment/asset-tx-payment", default-features = false, version = "28.0.0" }
pallet-assets = { path = "../../../substrate/frame/assets", default-features = false, version = "29.0.0" }
pallet-authorship = { path = "../../../substrate/frame/authorship", default-features = false, version = "28.0.0" }
pallet-balances = { path = "../../../substrate/frame/balances", default-features = false, version = "28.0.0" }
pallet-message-queue = { path = "../../../substrate/frame/message-queue", default-features = false, version = "31.0.0" }
sp-consensus-aura = { path = "../../../substrate/primitives/consensus/aura", default-features = false, version = "0.32.0" }
sp-core = { path = "../../../substrate/primitives/core", default-features = false, version = "28.0.0" }
sp-io = { path = "../../../substrate/primitives/io", default-features = false, version = "30.0.0" }
sp-runtime = { path = "../../../substrate/primitives/runtime", default-features = false, version = "31.0.0" }
sp-std = { path = "../../../substrate/primitives/std", default-features = false, version = "14.0.0" }

# Polkadot
pallet-xcm = { path = "../../../polkadot/xcm/pallet-xcm", default-features = false, version = "7.0.0" }
rococo-runtime-constants = { path = "../../../polkadot/runtime/rococo/constants", default-features = false, version = "7.0.0" }
westend-runtime-constants = { path = "../../../polkadot/runtime/westend/constants", default-features = false, version = "7.0.0" }
polkadot-core-primitives = { path = "../../../polkadot/core-primitives", default-features = false, version = "7.0.0" }
polkadot-primitives = { path = "../../../polkadot/primitives", default-features = false, version = "7.0.0" }
xcm = { package = "staging-xcm", path = "../../../polkadot/xcm", default-features = false, version = "7.0.0" }
xcm-builder = { package = "staging-xcm-builder", path = "../../../polkadot/xcm/xcm-builder", default-features = false, version = "7.0.3" }
xcm-executor = { package = "staging-xcm-executor", path = "../../../polkadot/xcm/xcm-executor", default-features = false, version = "7.0.3" }

# Cumulus
pallet-collator-selection = { path = "../../pallets/collator-selection", default-features = false, version = "9.0.2" }
cumulus-primitives-core = { path = "../../primitives/core", default-features = false, version = "0.7.0" }
cumulus-primitives-utility = { path = "../../primitives/utility", default-features = false, version = "0.7.3" }
parachain-info = { package = "staging-parachain-info", path = "../pallets/parachain-info", default-features = false, version = "0.7.0" }

[dev-dependencies]
pallet-authorship = { path = "../../../substrate/frame/authorship", default-features = false }
sp-io = { path = "../../../substrate/primitives/io", default-features = false }

[build-dependencies]
substrate-wasm-builder = { version = "17.0.0", path = "../../../substrate/utils/wasm-builder" }

[features]
default = ["std"]
std = [
	"codec/std",
	"cumulus-primitives-core/std",
	"cumulus-primitives-utility/std",
	"frame-support/std",
	"frame-system/std",
	"log/std",
	"num-traits/std",
	"pallet-asset-tx-payment/std",
	"pallet-assets/std",
	"pallet-authorship/std",
	"pallet-balances/std",
	"pallet-collator-selection/std",
	"pallet-message-queue/std",
	"pallet-xcm/std",
	"parachain-info/std",
	"polkadot-core-primitives/std",
	"polkadot-primitives/std",
	"rococo-runtime-constants/std",
	"scale-info/std",
	"sp-consensus-aura/std",
	"sp-core/std",
	"sp-io/std",
	"sp-runtime/std",
	"sp-std/std",
	"westend-runtime-constants/std",
	"xcm-builder/std",
	"xcm-executor/std",
	"xcm/std",
]

runtime-benchmarks = [
	"cumulus-primitives-core/runtime-benchmarks",
	"cumulus-primitives-utility/runtime-benchmarks",
	"frame-support/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
	"pallet-asset-tx-payment/runtime-benchmarks",
	"pallet-assets/runtime-benchmarks",
	"pallet-balances/runtime-benchmarks",
	"pallet-collator-selection/runtime-benchmarks",
	"pallet-message-queue/runtime-benchmarks",
	"pallet-xcm/runtime-benchmarks",
	"polkadot-primitives/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
	"xcm-builder/runtime-benchmarks",
	"xcm-executor/runtime-benchmarks",
]
