[package]
name = "frame-remote-externalities"
version = "0.35.0"
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
homepage = "https://substrate.io"
repository.workspace = true
description = "An externalities provided environment that can load itself from remote nodes or cached files"

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
jsonrpsee = { version = "0.16.2", features = ["http-client"] }
codec = { package = "parity-scale-codec", version = "3.6.1" }
log = "0.4.17"
serde = "1.0.195"
sp-core = { version = "28.0.0", path = "../../../primitives/core" }
sp-state-machine = { version = "0.35.0", path = "../../../primitives/state-machine" }
sp-io = { version = "30.0.0", path = "../../../primitives/io" }
sp-runtime = { version = "31.0.0", path = "../../../primitives/runtime" }
tokio = { version = "1.22.0", features = ["macros", "rt-multi-thread"] }
substrate-rpc-client = { version = "0.33.0", path = "../rpc/client" }
futures = "0.3"
indicatif = "0.17.3"
spinners = "4.1.0"
tokio-retry = "0.3.0"

[dev-dependencies]
sp-tracing = { path = "../../../primitives/tracing" }

[features]
remote-test = []
