[package]
name = "polkadot-core-primitives"
version = "7.0.0"
description = "Core Polkadot types used by Relay Chains and parachains."
authors.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
sp-core = { path = "../../substrate/primitives/core", default-features = false, version = "28.0.0" }
sp-std = { path = "../../substrate/primitives/std", default-features = false, version = "14.0.0" }
sp-runtime = { path = "../../substrate/primitives/runtime", default-features = false, version = "31.0.0" }
scale-info = { version = "2.10.0", default-features = false, features = ["derive"] }
parity-scale-codec = { version = "3.6.1", default-features = false, features = ["derive"] }

[features]
default = ["std"]
std = [
	"parity-scale-codec/std",
	"scale-info/std",
	"sp-core/std",
	"sp-runtime/std",
	"sp-std/std",
]
