[package]
name = "pallet-glutton"
version = "14.0.0"
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
homepage = "https://substrate.io"
repository.workspace = true
description = "FRAME pallet for pushing a chain to its weight limits"
readme = "README.md"

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
blake2 = { version = "0.10.4", default-features = false }
codec = { package = "parity-scale-codec", version = "3.6.1", default-features = false, features = ["derive"] }
scale-info = { version = "2.10.0", default-features = false, features = ["derive"] }
log = { version = "0.4.14", default-features = false }
frame-benchmarking = { path = "../benchmarking", default-features = false, optional = true, version = "28.0.0" }
frame-support = { path = "../support", default-features = false, version = "28.0.0" }
frame-system = { path = "../system", default-features = false, version = "28.0.0" }
sp-core = { path = "../../primitives/core", default-features = false, version = "28.0.0" }
sp-io = { path = "../../primitives/io", default-features = false, version = "30.0.0" }
sp-runtime = { path = "../../primitives/runtime", default-features = false, version = "31.0.0" }
sp-std = { path = "../../primitives/std", default-features = false, version = "14.0.0" }

[dev-dependencies]
pallet-balances = { path = "../balances" }

[features]
default = ["std"]
std = [
	"blake2/std",
	"codec/std",
	"frame-benchmarking?/std",
	"frame-support/std",
	"frame-system/std",
	"log/std",
	"scale-info/std",
	"sp-core/std",
	"sp-io/std",
	"sp-runtime/std",
	"sp-std/std",
]
try-runtime = [
	"frame-support/try-runtime",
	"frame-system/try-runtime",
	"sp-runtime/try-runtime",
]

runtime-benchmarks = [
	"frame-benchmarking/runtime-benchmarks",
	"frame-support/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
]
