[package]
name = "polkadot-node-jaeger"
version = "7.0.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
description = "Polkadot Jaeger primitives, but equally useful for Grafana/Tempo"

[lints]
workspace = true

[dependencies]
mick-jaeger = "0.1.8"
lazy_static = "1.4"
parking_lot = "0.12.1"
polkadot-primitives = { version = "7.0.0", path = "../../primitives" }
polkadot-node-primitives = { version = "7.0.0", path = "../primitives" }
sc-network = { version = "0.34.0", path = "../../../substrate/client/network" }
sp-core = { version = "28.0.0", path = "../../../substrate/primitives/core" }
thiserror = "1.0.48"
tokio = "1.24.2"
log = "0.4.17"
parity-scale-codec = { version = "3.6.1", default-features = false }
