[package]
name = "node-bench"
version = "0.1.0"
authors.workspace = true
description = "Substrate node integration benchmarks."
edition.workspace = true
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
homepage = "https://substrate.io"
repository.workspace = true
publish = false

[lints]
workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
array-bytes = "6.1"
clap = { version = "4.4.14", features = ["derive"] }
log = "0.4.17"
node-primitives = { version = "2.0.0", path = "../primitives" }
node-testing = { version = "0.1.0", path = "../testing" }
kitchensink-runtime = { version = "0.1.0", path = "../runtime" }
sc-client-api = { version = "28.0.0", path = "../../../client/api" }
sp-runtime = { version = "31.0.0", path = "../../../primitives/runtime" }
sp-state-machine = { version = "0.35.0", path = "../../../primitives/state-machine" }
serde = "1.0.195"
serde_json = "1.0.111"
derive_more = { version = "0.99.17", default-features = false, features = ["display"] }
kvdb = "0.13.0"
kvdb-rocksdb = "0.19.0"
sp-trie = { version = "29.0.0", path = "../../../primitives/trie" }
sp-core = { version = "28.0.0", path = "../../../primitives/core" }
sp-consensus = { version = "0.32.0", path = "../../../primitives/consensus/common" }
sc-basic-authorship = { version = "0.34.0", path = "../../../client/basic-authorship" }
sp-inherents = { version = "26.0.0", path = "../../../primitives/inherents" }
sp-timestamp = { path = "../../../primitives/timestamp", default-features = false, version = "26.0.0" }
sp-tracing = { version = "16.0.0", path = "../../../primitives/tracing" }
hash-db = "0.16.0"
tempfile = "3.1.0"
fs_extra = "1"
rand = { version = "0.8.5", features = ["small_rng"] }
lazy_static = "1.4.0"
parity-db = "0.4.12"
sc-transaction-pool = { version = "28.0.0", path = "../../../client/transaction-pool" }
sc-transaction-pool-api = { version = "28.0.0", path = "../../../client/transaction-pool/api" }
futures = { version = "0.3.21", features = ["thread-pool"] }
