[package]
name = "sc-executor"
version = "0.32.0"
authors.workspace = true
edition.workspace = true
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
homepage = "https://substrate.io"
repository.workspace = true
description = "A crate that provides means of executing/dispatching calls into the runtime."
documentation = "https://docs.rs/sc-executor"
readme = "README.md"

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
parking_lot = "0.12.1"
schnellru = "0.2.1"
tracing = "0.1.29"

codec = { package = "parity-scale-codec", version = "3.6.1" }
sc-executor-common = { version = "0.29.0", path = "common" }
sc-executor-wasmtime = { version = "0.29.0", path = "wasmtime" }
sp-api = { version = "26.0.0", path = "../../primitives/api" }
sp-core = { version = "28.0.0", path = "../../primitives/core" }
sp-externalities = { version = "0.25.0", path = "../../primitives/externalities" }
sp-io = { version = "30.0.0", path = "../../primitives/io" }
sp-panic-handler = { version = "13.0.0", path = "../../primitives/panic-handler" }
sp-runtime-interface = { version = "24.0.0", path = "../../primitives/runtime-interface" }
sp-trie = { version = "29.0.0", path = "../../primitives/trie" }
sp-version = { version = "29.0.0", path = "../../primitives/version" }
sp-wasm-interface = { version = "20.0.0", path = "../../primitives/wasm-interface" }

[dev-dependencies]
array-bytes = "6.1"
assert_matches = "1.3.0"
wat = "1.0"
sc-runtime-test = { path = "runtime-test" }
substrate-test-runtime = { path = "../../test-utils/runtime" }
sp-state-machine = { path = "../../primitives/state-machine" }
sp-runtime = { path = "../../primitives/runtime" }
sp-maybe-compressed-blob = { path = "../../primitives/maybe-compressed-blob" }
sc-tracing = { path = "../tracing" }
sp-tracing = { path = "../../primitives/tracing" }
tracing-subscriber = "0.2.19"
paste = "1.0"
regex = "1.6.0"
criterion = "0.4.0"
env_logger = "0.9"
num_cpus = "1.13.1"
tempfile = "3.3.0"

[[bench]]
name = "bench"
harness = false

[features]
default = ["std"]
# This crate does not have `no_std` support, we just require this for tests
std = [
	"sp-api/std",
	"sp-core/std",
	"sp-externalities/std",
	"sp-io/std",
	"sp-runtime-interface/std",
	"sp-trie/std",
	"sp-version/std",
	"sp-wasm-interface/std",
]
wasm-extern-trace = []
