[package]
name = "snowbridge-rococo-common"
description = "Snowbridge Rococo Common"
version = "0.1.0"
authors = ["Snowfork <contact@snowfork.com>"]
edition = "2021"
license = "Apache-2.0"

[dependencies]
log = { version = "0.4.20", default-features = false }

frame-support = { path = "../../../../../substrate/frame/support", default-features = false, version = "28.0.0" }
xcm = { package = "staging-xcm", path = "../../../../../polkadot/xcm", default-features = false, version = "7.0.0" }

[dev-dependencies]

[features]
default = ["std"]
std = [
	"frame-support/std",
	"log/std",
	"xcm/std",
]
runtime-benchmarks = [
	"frame-support/runtime-benchmarks",
]
