[package]
name = "polkadot-voter-bags"
version = "7.0.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
description = "CLI to generate voter bags for Polkadot runtimes"

[lints]
workspace = true

[dependencies]
clap = { version = "4.4.14", features = ["derive"] }
generate-bags = { version = "28.0.0", path = "../../../substrate/utils/frame/generate-bags" }
sp-io = { version = "30.0.0", path = "../../../substrate/primitives/io" }
westend-runtime = { version = "7.0.0", path = "../../runtime/westend" }
