[package]
name = "snowbridge-ethereum-beacon-client"
description = "Snowbridge Beacon Client Pallet"
version = "0.1.0"
edition = "2021"
authors = ["Snowfork <contact@snowfork.com>"]
repository = "https://github.com/Snowfork/snowbridge"
license = "Apache-2.0"
publish = false

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
serde = { version = "1.0.195", optional = true }
serde_json = { version = "1.0.111", optional = true }
codec = { version = "3.6.1", package = "parity-scale-codec", default-features = false, features = ["derive"] }
scale-info = { version = "2.9.0", default-features = false, features = ["derive"] }
ssz_rs = { version = "0.9.0", default-features = false }
ssz_rs_derive = { version = "0.9.0", default-features = false }
byte-slice-cast = { version = "1.2.1", default-features = false }
rlp = { version = "0.5.2", default-features = false }
hex-literal = { version = "0.4.1", optional = true }
log = { version = "0.4.20", default-features = false }

frame-benchmarking = { path = "../../../../../substrate/frame/benchmarking", default-features = false, optional = true, version = "28.0.0" }
frame-support = { path = "../../../../../substrate/frame/support", default-features = false, version = "28.0.0" }
frame-system = { path = "../../../../../substrate/frame/system", default-features = false, version = "28.0.0" }
sp-core = { path = "../../../../../substrate/primitives/core", default-features = false, version = "28.0.0" }
sp-std = { path = "../../../../../substrate/primitives/std", default-features = false, version = "14.0.0" }
sp-runtime = { path = "../../../../../substrate/primitives/runtime", default-features = false, version = "31.0.0" }
sp-io = { path = "../../../../../substrate/primitives/io", default-features = false, optional = true, version = "30.0.0" }

snowbridge-core = { path = "../../primitives/core", default-features = false, version = "0.1.0" }
snowbridge-ethereum = { path = "../../primitives/ethereum", default-features = false, version = "0.1.0" }
primitives = { package = "snowbridge-beacon-primitives", path = "../../primitives/beacon", default-features = false, version = "0.1.0" }
static_assertions = { version = "1.1.0", default-features = false }
bp-runtime = { path = "../../../../primitives/runtime", default-features = false, version = "0.7.0" }
pallet-timestamp = { path = "../../../../../substrate/frame/timestamp", default-features = false, optional = true, version = "27.0.0" }

[dev-dependencies]
rand = "0.8.5"
sp-keyring = { path = "../../../../../substrate/primitives/keyring" }
serde_json = "1.0.111"
hex-literal = "0.4.1"
pallet-timestamp = { path = "../../../../../substrate/frame/timestamp" }
sp-io = { path = "../../../../../substrate/primitives/io" }
serde = "1.0.195"

[features]
default = ["std"]
fuzzing = [
	"hex-literal",
	"pallet-timestamp",
	"serde",
	"serde_json",
	"sp-io",
]
std = [
	"bp-runtime/std",
	"byte-slice-cast/std",
	"codec/std",
	"frame-support/std",
	"frame-system/std",
	"log/std",
	"pallet-timestamp/std",
	"primitives/std",
	"rlp/std",
	"scale-info/std",
	"serde",
	"snowbridge-core/std",
	"snowbridge-ethereum/std",
	"sp-core/std",
	"sp-io/std",
	"sp-runtime/std",
	"sp-std/std",
	"ssz_rs/std",
	'frame-benchmarking/std',
]
runtime-benchmarks = [
	"frame-benchmarking/runtime-benchmarks",
	"frame-support/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
	"hex-literal",
	"pallet-timestamp?/runtime-benchmarks",
	"snowbridge-core/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
]
try-runtime = [
	"frame-support/try-runtime",
	"frame-system/try-runtime",
	"pallet-timestamp?/try-runtime",
	"sp-runtime/try-runtime",
]
beacon-spec-minimal = []
fast-runtime = ["beacon-spec-minimal"]
