[package]
name = "pallet-nomination-pools-benchmarking"
version = "26.0.0"
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
homepage = "https://substrate.io"
repository.workspace = true
description = "FRAME nomination pools pallet benchmarking"
readme = "README.md"

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
# parity
codec = { package = "parity-scale-codec", version = "3.6.1", default-features = false, features = ["derive"] }
scale-info = { version = "2.10.0", default-features = false, features = ["derive"] }

# FRAME
frame-benchmarking = { path = "../../benchmarking", default-features = false, version = "28.0.0" }
frame-election-provider-support = { path = "../../election-provider-support", default-features = false, version = "28.0.0" }
frame-support = { path = "../../support", default-features = false, version = "28.0.0" }
frame-system = { path = "../../system", default-features = false, version = "28.0.0" }
pallet-bags-list = { path = "../../bags-list", default-features = false, version = "27.0.0" }
pallet-staking = { path = "../../staking", default-features = false, version = "28.0.1" }
pallet-nomination-pools = { path = "..", default-features = false, version = "25.0.3" }

# Substrate Primitives
sp-runtime = { path = "../../../primitives/runtime", default-features = false, version = "31.0.0" }
sp-runtime-interface = { path = "../../../primitives/runtime-interface", default-features = false, version = "24.0.0" }
sp-staking = { path = "../../../primitives/staking", default-features = false, version = "26.0.0" }
sp-std = { path = "../../../primitives/std", default-features = false, version = "14.0.0" }

[dev-dependencies]
pallet-balances = { path = "../../balances", default-features = false }
pallet-timestamp = { path = "../../timestamp" }
pallet-staking-reward-curve = { path = "../../staking/reward-curve" }
sp-core = { path = "../../../primitives/core" }
sp-io = { path = "../../../primitives/io" }

[features]
default = ["std"]

std = [
	"codec/std",
	"frame-benchmarking/std",
	"frame-election-provider-support/std",
	"frame-support/std",
	"frame-system/std",
	"pallet-bags-list/std",
	"pallet-nomination-pools/std",
	"pallet-staking/std",
	"scale-info/std",
	"sp-runtime-interface/std",
	"sp-runtime/std",
	"sp-staking/std",
	"sp-std/std",
]

runtime-benchmarks = [
	"frame-benchmarking/runtime-benchmarks",
	"frame-election-provider-support/runtime-benchmarks",
	"frame-support/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
	"pallet-bags-list/runtime-benchmarks",
	"pallet-nomination-pools/runtime-benchmarks",
	"pallet-staking/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
	"sp-staking/runtime-benchmarks",
]
