[package]
name = "frame-benchmarking-cli"
version = "32.0.0"
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
homepage = "https://substrate.io"
repository.workspace = true
description = "CLI for benchmarking FRAME"
readme = "README.md"

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
array-bytes = "6.1"
chrono = "0.4"
clap = { version = "4.4.14", features = ["derive"] }
codec = { package = "parity-scale-codec", version = "3.6.1" }
comfy-table = { version = "7.0.1", default-features = false }
handlebars = "4.2.2"
Inflector = "0.11.4"
itertools = "0.10.3"
lazy_static = "1.4.0"
linked-hash-map = "0.5.4"
log = "0.4.17"
rand = { version = "0.8.5", features = ["small_rng"] }
rand_pcg = "0.3.1"
serde = "1.0.195"
serde_json = "1.0.111"
thiserror = "1.0.48"
thousands = "0.2.0"
frame-benchmarking = { version = "28.0.0", path = "../../../frame/benchmarking" }
frame-support = { version = "28.0.0", path = "../../../frame/support" }
frame-system = { version = "28.0.0", path = "../../../frame/system" }
sc-block-builder = { version = "0.33.0", path = "../../../client/block-builder" }
sc-cli = { path = "../../../client/cli", default-features = false, version = "0.36.0" }
sc-client-api = { version = "28.0.0", path = "../../../client/api" }
sc-client-db = { path = "../../../client/db", default-features = false, version = "0.35.0" }
sc-executor = { version = "0.32.0", path = "../../../client/executor" }
sc-service = { path = "../../../client/service", default-features = false, version = "0.35.0" }
sc-sysinfo = { version = "27.0.0", path = "../../../client/sysinfo" }
sp-api = { version = "26.0.0", path = "../../../primitives/api" }
sp-blockchain = { version = "28.0.0", path = "../../../primitives/blockchain" }
sp-core = { version = "28.0.0", path = "../../../primitives/core" }
sp-database = { version = "10.0.0", path = "../../../primitives/database" }
sp-externalities = { version = "0.25.0", path = "../../../primitives/externalities" }
sp-inherents = { version = "26.0.0", path = "../../../primitives/inherents" }
sp-keystore = { version = "0.34.0", path = "../../../primitives/keystore" }
sp-runtime = { version = "31.0.0", path = "../../../primitives/runtime" }
sp-state-machine = { version = "0.35.0", path = "../../../primitives/state-machine" }
sp-storage = { version = "19.0.0", path = "../../../primitives/storage" }
sp-trie = { version = "29.0.0", path = "../../../primitives/trie" }
sp-io = { version = "30.0.0", path = "../../../primitives/io" }
sp-wasm-interface = { version = "20.0.0", path = "../../../primitives/wasm-interface" }
gethostname = "0.2.3"

[features]
default = ["rocksdb"]
runtime-benchmarks = [
	"frame-benchmarking/runtime-benchmarks",
	"frame-support/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
	"sc-client-db/runtime-benchmarks",
	"sc-service/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
]
rocksdb = ["sc-cli/rocksdb", "sc-client-db/rocksdb"]
