[package]
name = "sc-rpc-spec-v2"
version = "0.34.0"
authors.workspace = true
edition.workspace = true
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
homepage = "https://substrate.io"
repository.workspace = true
description = "Substrate RPC interface v2."
readme = "README.md"

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
jsonrpsee = { version = "0.16.2", features = ["client-core", "macros", "server"] }
sc-chain-spec = { version = "27.0.0", path = "../chain-spec" }
sc-transaction-pool-api = { version = "28.0.0", path = "../transaction-pool/api" }
sp-core = { version = "28.0.0", path = "../../primitives/core" }
sp-runtime = { version = "31.0.0", path = "../../primitives/runtime" }
sp-api = { version = "26.0.0", path = "../../primitives/api" }
sp-rpc = { version = "26.0.0", path = "../../primitives/rpc" }
sp-blockchain = { version = "28.0.0", path = "../../primitives/blockchain" }
sp-version = { version = "29.0.0", path = "../../primitives/version" }
sc-client-api = { version = "28.0.0", path = "../api" }
sc-utils = { version = "14.0.0", path = "../utils" }
codec = { package = "parity-scale-codec", version = "3.6.1" }
thiserror = "1.0"
serde = "1.0"
hex = "0.4"
futures = "0.3.21"
parking_lot = "0.12.1"
tokio-stream = { version = "0.1.14", features = ["sync"] }
tokio = { version = "1.22.0", features = ["sync"] }
array-bytes = "6.1"
log = "0.4.17"
futures-util = { version = "0.3.19", default-features = false }

[dev-dependencies]
serde_json = "1.0.111"
tokio = { version = "1.22.0", features = ["macros"] }
substrate-test-runtime-client = { path = "../../test-utils/runtime/client" }
substrate-test-runtime = { path = "../../test-utils/runtime" }
sp-consensus = { path = "../../primitives/consensus/common" }
sp-externalities = { path = "../../primitives/externalities" }
sp-maybe-compressed-blob = { path = "../../primitives/maybe-compressed-blob" }
sc-block-builder = { path = "../block-builder" }
sc-service = { path = "../service", features = ["test-helpers"] }
assert_matches = "1.3.0"
pretty_assertions = "1.2.1"
