[package]
name = "polkadot-statement-distribution"
description = "Statement Distribution Subsystem"
version = "7.0.0"
authors.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
futures = "0.3.21"
futures-timer = "3.0.2"
gum = { package = "tracing-gum", path = "../../gum", version = "7.0.0" }
polkadot-primitives = { version = "7.0.0", path = "../../../primitives" }
sp-staking = { path = "../../../../substrate/primitives/staking", default-features = false, version = "26.0.0" }
sp-keystore = { version = "0.34.0", path = "../../../../substrate/primitives/keystore" }
polkadot-node-subsystem = { version = "7.0.0", path = "../../subsystem" }
polkadot-node-primitives = { version = "7.0.0", path = "../../primitives" }
polkadot-node-subsystem-util = { version = "7.0.0", path = "../../subsystem-util" }
polkadot-node-network-protocol = { version = "7.0.0", path = "../protocol" }
arrayvec = "0.7.4"
indexmap = "1.9.1"
parity-scale-codec = { version = "3.6.1", default-features = false, features = ["derive"] }
thiserror = "1.0.48"
fatality = "0.0.6"
bitvec = "1"

[dev-dependencies]
async-channel = "1.8.0"
assert_matches = "1.4.0"
polkadot-node-subsystem-test-helpers = { path = "../../subsystem-test-helpers" }
sp-authority-discovery = { path = "../../../../substrate/primitives/authority-discovery" }
sp-keyring = { path = "../../../../substrate/primitives/keyring" }
sp-core = { path = "../../../../substrate/primitives/core" }
sp-application-crypto = { path = "../../../../substrate/primitives/application-crypto" }
sp-keystore = { path = "../../../../substrate/primitives/keystore" }
sp-tracing = { path = "../../../../substrate/primitives/tracing" }
sc-keystore = { path = "../../../../substrate/client/keystore" }
sc-network = { path = "../../../../substrate/client/network" }
futures-timer = "3.0.2"
polkadot-primitives-test-helpers = { path = "../../../primitives/test-helpers" }
rand_chacha = "0.3"
