[package]
name = "staging-node-cli"
version = "0.1.0"
authors.workspace = true
description = "Generic Substrate node implementation in Rust."
build = "build.rs"
edition.workspace = true
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
default-run = "substrate-node"
homepage = "https://substrate.io"
repository.workspace = true
publish = false

[lints]
workspace = true

[package.metadata.wasm-pack.profile.release]
# `wasm-opt` has some problems on linux, see
# https://github.com/rustwasm/wasm-pack/issues/781 etc.
wasm-opt = false

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[badges]
travis-ci = { repository = "paritytech/substrate" }
maintenance = { status = "actively-developed" }
is-it-maintained-issue-resolution = { repository = "paritytech/substrate" }
is-it-maintained-open-issues = { repository = "paritytech/substrate" }

# The same node binary as the `substrate` (defined in the workspace `Cargo.toml`) binary,
# but just exposed by this crate here.
[[bin]]
name = "substrate-node"
path = "bin/main.rs"
required-features = ["cli"]

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
# third-party dependencies
array-bytes = "6.1"
clap = { version = "4.4.14", features = ["derive"], optional = true }
codec = { package = "parity-scale-codec", version = "3.6.1" }
serde = { version = "1.0.195", features = ["derive"] }
jsonrpsee = { version = "0.16.2", features = ["server"] }
futures = "0.3.21"
log = "0.4.17"
rand = "0.8"
sp-authority-discovery = { version = "26.0.0", path = "../../../primitives/authority-discovery" }
sp-consensus-babe = { version = "0.32.0", path = "../../../primitives/consensus/babe" }
beefy-primitives = { package = "sp-consensus-beefy", path = "../../../primitives/consensus/beefy", version = "13.0.0" }
grandpa-primitives = { package = "sp-consensus-grandpa", path = "../../../primitives/consensus/grandpa", version = "13.0.0" }
sp-api = { version = "26.0.0", path = "../../../primitives/api" }
sp-core = { version = "28.0.0", path = "../../../primitives/core" }
sp-runtime = { version = "31.0.0", path = "../../../primitives/runtime" }
sp-timestamp = { version = "26.0.0", path = "../../../primitives/timestamp" }
sp-inherents = { version = "26.0.0", path = "../../../primitives/inherents" }
sp-keyring = { version = "31.0.0", path = "../../../primitives/keyring" }
sp-keystore = { version = "0.34.0", path = "../../../primitives/keystore" }
sp-consensus = { version = "0.32.0", path = "../../../primitives/consensus/common" }
sp-transaction-storage-proof = { version = "26.0.0", path = "../../../primitives/transaction-storage-proof" }
sp-io = { version = "30.0.0", path = "../../../primitives/io" }
sp-mixnet = { version = "0.4.0", path = "../../../primitives/mixnet" }
sp-mmr-primitives = { version = "26.0.0", path = "../../../primitives/merkle-mountain-range" }
sp-statement-store = { version = "10.0.0", path = "../../../primitives/statement-store" }
sc-client-api = { version = "28.0.0", path = "../../../client/api" }
sc-chain-spec = { version = "27.0.0", path = "../../../client/chain-spec" }
sc-consensus = { version = "0.33.0", path = "../../../client/consensus/common" }
sc-transaction-pool = { version = "28.0.0", path = "../../../client/transaction-pool" }
sc-transaction-pool-api = { version = "28.0.0", path = "../../../client/transaction-pool/api" }
sc-statement-store = { version = "10.0.0", path = "../../../client/statement-store" }
sc-network = { version = "0.34.0", path = "../../../client/network" }
sc-network-common = { version = "0.33.0", path = "../../../client/network/common" }
sc-network-sync = { version = "0.33.0", path = "../../../client/network/sync" }
sc-network-statement = { version = "0.16.0", path = "../../../client/network/statement" }
sc-consensus-slots = { version = "0.33.0", path = "../../../client/consensus/slots" }
sc-consensus-babe = { version = "0.34.0", path = "../../../client/consensus/babe" }
beefy = { package = "sc-consensus-beefy", path = "../../../client/consensus/beefy", version = "13.0.0" }
grandpa = { package = "sc-consensus-grandpa", path = "../../../client/consensus/grandpa", version = "0.19.0" }
mmr-gadget = { version = "29.0.0", path = "../../../client/merkle-mountain-range" }
sc-rpc = { version = "29.0.0", path = "../../../client/rpc" }
sc-basic-authorship = { version = "0.34.0", path = "../../../client/basic-authorship" }
sc-service = { path = "../../../client/service", default-features = false, version = "0.35.0" }
sc-telemetry = { version = "15.0.0", path = "../../../client/telemetry" }
sc-executor = { version = "0.32.0", path = "../../../client/executor" }
sc-authority-discovery = { version = "0.34.0", path = "../../../client/authority-discovery" }
sc-mixnet = { version = "0.4.0", path = "../../../client/mixnet" }
sc-sync-state-rpc = { version = "0.34.0", path = "../../../client/sync-state-rpc" }
sc-sysinfo = { version = "27.0.0", path = "../../../client/sysinfo" }
sc-storage-monitor = { version = "0.16.0", path = "../../../client/storage-monitor" }
sc-offchain = { version = "29.0.0", path = "../../../client/offchain" }
frame-benchmarking = { version = "28.0.0", path = "../../../frame/benchmarking" }
frame-system = { version = "28.0.0", path = "../../../frame/system" }
frame-system-rpc-runtime-api = { version = "26.0.0", path = "../../../frame/system/rpc/runtime-api" }
pallet-assets = { version = "29.0.0", path = "../../../frame/assets" }
pallet-asset-conversion-tx-payment = { version = "10.0.0", path = "../../../frame/transaction-payment/asset-conversion-tx-payment" }
pallet-asset-tx-payment = { version = "28.0.0", path = "../../../frame/transaction-payment/asset-tx-payment" }
pallet-im-online = { path = "../../../frame/im-online", default-features = false, version = "27.0.0" }
pallet-skip-feeless-payment = { path = "../../../frame/transaction-payment/skip-feeless-payment", default-features = false, version = "3.0.0" }
kitchensink-runtime = { version = "0.1.0", path = "../runtime" }
node-rpc = { version = "0.1.0", path = "../rpc" }
node-primitives = { version = "2.0.0", path = "../primitives" }

# CLI-specific dependencies
sc-cli = { path = "../../../client/cli", optional = true, version = "0.36.0" }
frame-benchmarking-cli = { path = "../../../utils/frame/benchmarking-cli", optional = true, version = "32.0.0" }
node-inspect = { package = "staging-node-inspect", path = "../inspect", optional = true, version = "0.12.0" }
try-runtime-cli = { path = "../../../utils/frame/try-runtime/cli", optional = true, version = "0.38.0" }
serde_json = "1.0.111"

[dev-dependencies]
sc-keystore = { path = "../../../client/keystore" }
sc-client-db = { path = "../../../client/db" }
sc-consensus = { path = "../../../client/consensus/common" }
sc-consensus-babe = { path = "../../../client/consensus/babe" }
sc-consensus-epochs = { path = "../../../client/consensus/epochs" }
sc-service-test = { path = "../../../client/service/test" }
sc-block-builder = { path = "../../../client/block-builder" }
sp-tracing = { path = "../../../primitives/tracing" }
sp-blockchain = { path = "../../../primitives/blockchain" }
futures = "0.3.21"
tempfile = "3.1.0"
assert_cmd = "2.0.2"
nix = { version = "0.26.1", features = ["signal"] }
regex = "1.6.0"
platforms = "3.0"
soketto = "0.7.1"
criterion = { version = "0.4.0", features = ["async_tokio"] }
tokio = { version = "1.22.0", features = ["macros", "parking_lot", "time"] }
tokio-util = { version = "0.7.4", features = ["compat"] }
wait-timeout = "0.2"
substrate-rpc-client = { path = "../../../utils/frame/rpc/client" }
pallet-timestamp = { path = "../../../frame/timestamp" }
substrate-cli-test-utils = { path = "../../../test-utils/cli" }

wat = "1.0"
frame-support = { path = "../../../frame/support" }
node-testing = { path = "../testing" }
pallet-balances = { path = "../../../frame/balances" }
pallet-contracts = { path = "../../../frame/contracts" }
pallet-glutton = { path = "../../../frame/glutton" }
pallet-sudo = { path = "../../../frame/sudo" }
pallet-treasury = { path = "../../../frame/treasury" }
pallet-transaction-payment = { path = "../../../frame/transaction-payment" }
sp-application-crypto = { path = "../../../primitives/application-crypto" }
pallet-root-testing = { path = "../../../frame/root-testing" }
sp-consensus-babe = { path = "../../../primitives/consensus/babe" }
sp-externalities = { path = "../../../primitives/externalities" }
sp-keyring = { path = "../../../primitives/keyring" }
sp-runtime = { path = "../../../primitives/runtime" }
serde_json = "1.0.111"
scale-info = { version = "2.10.0", features = ["derive", "serde"] }
sp-trie = { path = "../../../primitives/trie" }
sp-state-machine = { path = "../../../primitives/state-machine" }

[build-dependencies]
clap = { version = "4.4.14", optional = true }
clap_complete = { version = "4.0.2", optional = true }
node-inspect = { package = "staging-node-inspect", path = "../inspect", optional = true, version = "0.12.0" }
frame-benchmarking-cli = { path = "../../../utils/frame/benchmarking-cli", optional = true, version = "32.0.0" }
substrate-build-script-utils = { path = "../../../utils/build-script-utils", optional = true, version = "11.0.0" }
substrate-frame-cli = { path = "../../../utils/frame/frame-utilities-cli", optional = true, version = "32.0.0" }
try-runtime-cli = { path = "../../../utils/frame/try-runtime/cli", optional = true, version = "0.38.0" }
sc-cli = { path = "../../../client/cli", optional = true, version = "0.36.0" }
pallet-balances = { version = "28.0.0", path = "../../../frame/balances" }
sc-storage-monitor = { version = "0.16.0", path = "../../../client/storage-monitor" }

[features]
default = ["cli"]
cli = [
	"clap",
	"clap_complete",
	"frame-benchmarking-cli",
	"node-inspect",
	"sc-cli",
	"sc-service/rocksdb",
	"substrate-build-script-utils",
	"substrate-frame-cli",
	"try-runtime-cli",
]
runtime-benchmarks = [
	"frame-benchmarking-cli/runtime-benchmarks",
	"frame-benchmarking/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
	"kitchensink-runtime/runtime-benchmarks",
	"node-inspect?/runtime-benchmarks",
	"pallet-asset-tx-payment/runtime-benchmarks",
	"pallet-assets/runtime-benchmarks",
	"pallet-balances/runtime-benchmarks",
	"pallet-im-online/runtime-benchmarks",
	"pallet-skip-feeless-payment/runtime-benchmarks",
	"sc-service/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
]
# Enable features that allow the runtime to be tried and debugged. Name might be subject to change
# in the near future.
try-runtime = [
	"frame-system/try-runtime",
	"kitchensink-runtime/try-runtime",
	"pallet-asset-conversion-tx-payment/try-runtime",
	"pallet-asset-tx-payment/try-runtime",
	"pallet-assets/try-runtime",
	"pallet-balances/try-runtime",
	"pallet-im-online/try-runtime",
	"pallet-skip-feeless-payment/try-runtime",
	"sp-runtime/try-runtime",
	"try-runtime-cli/try-runtime",
]

[[bench]]
name = "transaction_pool"
harness = false

[[bench]]
name = "block_production"
harness = false

[[bench]]
name = "executor"
harness = false
