[package]
name = "cumulus-primitives-core"
version = "0.7.0"
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
description = "Cumulus related core primitive types and traits"

[lints]
workspace = true

[dependencies]
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive"] }
scale-info = { version = "2.10.0", default-features = false, features = ["derive"] }

# Substrate
sp-api = { path = "../../../substrate/primitives/api", default-features = false, version = "26.0.0" }
sp-runtime = { path = "../../../substrate/primitives/runtime", default-features = false, version = "31.0.0" }
sp-std = { path = "../../../substrate/primitives/std", default-features = false, version = "14.0.0" }
sp-trie = { path = "../../../substrate/primitives/trie", default-features = false, version = "29.0.0" }

# Polkadot
polkadot-core-primitives = { path = "../../../polkadot/core-primitives", default-features = false, version = "7.0.0" }
polkadot-parachain-primitives = { path = "../../../polkadot/parachain", default-features = false, version = "6.0.0" }
polkadot-primitives = { path = "../../../polkadot/primitives", default-features = false, version = "7.0.0" }
xcm = { package = "staging-xcm", path = "../../../polkadot/xcm", default-features = false, version = "7.0.0" }

[features]
default = ["std"]
std = [
	"codec/std",
	"polkadot-core-primitives/std",
	"polkadot-parachain-primitives/std",
	"polkadot-primitives/std",
	"scale-info/std",
	"sp-api/std",
	"sp-runtime/std",
	"sp-std/std",
	"sp-trie/std",
	"xcm/std",
]
runtime-benchmarks = [
	"polkadot-parachain-primitives/runtime-benchmarks",
	"polkadot-primitives/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
]
