[package]
name = "xcm-emulator"
description = "Test kit to emulate XCM program execution."
version = "0.5.0"
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"

[lints]
workspace = true

[dependencies]
codec = { package = "parity-scale-codec", version = "3.0.0" }
paste = "1.0.14"
log = { version = "0.4.20", default-features = false }
lazy_static = "1.4.0"
impl-trait-for-tuples = "0.2.2"
frame-support = { version = "28.0.0", path = "../../../substrate/frame/support" }
frame-system = { version = "28.0.0", path = "../../../substrate/frame/system" }
sp-io = { version = "30.0.0", path = "../../../substrate/primitives/io" }
sp-core = { version = "28.0.0", path = "../../../substrate/primitives/core" }
sp-std = { version = "14.0.0", path = "../../../substrate/primitives/std" }
sp-runtime = { version = "31.0.0", path = "../../../substrate/primitives/runtime" }
sp-arithmetic = { version = "23.0.0", path = "../../../substrate/primitives/arithmetic" }
sp-tracing = { version = "16.0.0", path = "../../../substrate/primitives/tracing" }
pallet-balances = { version = "28.0.0", path = "../../../substrate/frame/balances" }
pallet-message-queue = { version = "31.0.0", path = "../../../substrate/frame/message-queue" }
cumulus-primitives-core = { version = "0.7.0", path = "../../primitives/core" }
cumulus-pallet-xcmp-queue = { version = "0.7.0", path = "../../pallets/xcmp-queue" }
cumulus-pallet-parachain-system = { version = "0.7.0", path = "../../pallets/parachain-system" }
cumulus-primitives-parachain-inherent = { version = "0.7.0", path = "../../primitives/parachain-inherent" }
cumulus-test-relay-sproof-builder = { version = "0.7.0", path = "../../test/relay-sproof-builder" }
parachains-common = { version = "7.0.0", path = "../../parachains/common" }

# Polkadot
xcm = { package = "staging-xcm", path = "../../../polkadot/xcm", version = "7.0.0" }
xcm-executor = { package = "staging-xcm-executor", path = "../../../polkadot/xcm/xcm-executor", version = "7.0.3" }
polkadot-primitives = { version = "7.0.0", path = "../../../polkadot/primitives" }
polkadot-parachain-primitives = { version = "6.0.0", path = "../../../polkadot/parachain" }
polkadot-runtime-parachains = { version = "7.0.0", path = "../../../polkadot/runtime/parachains" }
