[package]
name = "sp-blockchain"
version = "28.0.0"
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
homepage = "https://substrate.io"
repository.workspace = true
description = "Substrate blockchain traits and primitives."
documentation = "https://docs.rs/sp-blockchain"
readme = "README.md"

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "3.6.1", default-features = false, features = ["derive"] }
futures = "0.3.21"
log = "0.4.17"
parking_lot = "0.12.1"
schnellru = "0.2.1"
thiserror = "1.0.48"
sp-api = { version = "26.0.0", path = "../api" }
sp-consensus = { version = "0.32.0", path = "../consensus/common" }
sp-database = { version = "10.0.0", path = "../database" }
sp-runtime = { version = "31.0.0", path = "../runtime" }
sp-state-machine = { version = "0.35.0", path = "../state-machine" }
