[package]
name = "polkadot-node-core-chain-api"
version = "7.0.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
description = "The Chain API subsystem provides access to chain related utility functions like block number to hash conversions."

[lints]
workspace = true

[dependencies]
futures = "0.3.21"
gum = { package = "tracing-gum", path = "../../gum", version = "7.0.0" }
polkadot-node-metrics = { version = "7.0.0", path = "../../metrics" }
polkadot-node-subsystem = { version = "7.0.0", path = "../../subsystem" }
polkadot-node-subsystem-types = { version = "7.0.0", path = "../../subsystem-types" }
sc-client-api = { version = "28.0.0", path = "../../../../substrate/client/api" }
sc-consensus-babe = { version = "0.34.0", path = "../../../../substrate/client/consensus/babe" }

[dev-dependencies]
futures = { version = "0.3.21", features = ["thread-pool"] }
maplit = "1.0.2"
parity-scale-codec = "3.6.1"
polkadot-node-primitives = { path = "../../primitives" }
polkadot-primitives = { path = "../../../primitives" }
polkadot-node-subsystem-test-helpers = { path = "../../subsystem-test-helpers" }
sp-core = { path = "../../../../substrate/primitives/core" }
sp-blockchain = { path = "../../../../substrate/primitives/blockchain" }
