[package]
description = "Substrate offchain workers"
name = "sc-offchain"
version = "29.0.0"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
authors.workspace = true
edition.workspace = true
homepage = "https://substrate.io"
repository.workspace = true
readme = "README.md"

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
array-bytes = "6.1"
bytes = "1.1"
codec = { package = "parity-scale-codec", version = "3.6.1", features = ["derive"] }
fnv = "1.0.6"
futures = "0.3.21"
futures-timer = "3.0.2"
hyper = { version = "0.14.16", features = ["http2", "stream"] }
hyper-rustls = { version = "0.24.0", features = ["http2"] }
libp2p = "0.51.4"
num_cpus = "1.13"
once_cell = "1.8"
parking_lot = "0.12.1"
rand = "0.8.5"
threadpool = "1.7"
tracing = "0.1.29"
sc-client-api = { version = "28.0.0", path = "../api" }
sc-network = { version = "0.34.0", path = "../network" }
sc-network-common = { version = "0.33.0", path = "../network/common" }
sc-transaction-pool-api = { version = "28.0.0", path = "../transaction-pool/api" }
sc-utils = { version = "14.0.0", path = "../utils" }
sp-api = { version = "26.0.0", path = "../../primitives/api" }
sp-core = { version = "28.0.0", path = "../../primitives/core" }
sp-offchain = { version = "26.0.0", path = "../../primitives/offchain" }
sp-runtime = { version = "31.0.0", path = "../../primitives/runtime" }
sp-keystore = { version = "0.34.0", path = "../../primitives/keystore" }
sp-externalities = { version = "0.25.0", path = "../../primitives/externalities" }
log = "0.4.17"

[dev-dependencies]
lazy_static = "1.4.0"
tokio = "1.22.0"
sc-block-builder = { path = "../block-builder" }
sc-client-db = { path = "../db", default-features = true }
sc-transaction-pool = { path = "../transaction-pool" }
sc-transaction-pool-api = { path = "../transaction-pool/api" }
sp-consensus = { path = "../../primitives/consensus/common" }
sp-tracing = { path = "../../primitives/tracing" }
substrate-test-runtime-client = { path = "../../test-utils/runtime/client" }

[features]
default = []
