[package]
name = "pallet-bridge-grandpa"
version = "0.7.0"
description = "Module implementing GRANDPA on-chain light client used for bridging consensus of substrate-based chains."
authors.workspace = true
edition.workspace = true
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"

[lints]
workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
codec = { package = "parity-scale-codec", version = "3.1.5", default-features = false }
finality-grandpa = { version = "0.16.2", default-features = false }
log = { version = "0.4.20", default-features = false }
scale-info = { version = "2.10.0", default-features = false, features = ["derive"] }

# Bridge Dependencies

bp-runtime = { path = "../../primitives/runtime", default-features = false, version = "0.7.0" }
bp-header-chain = { path = "../../primitives/header-chain", default-features = false, version = "0.7.0" }

# Substrate Dependencies

frame-support = { path = "../../../substrate/frame/support", default-features = false, version = "28.0.0" }
frame-system = { path = "../../../substrate/frame/system", default-features = false, version = "28.0.0" }
sp-consensus-grandpa = { path = "../../../substrate/primitives/consensus/grandpa", default-features = false, features = ["serde"], version = "13.0.0" }
sp-runtime = { path = "../../../substrate/primitives/runtime", default-features = false, features = ["serde"], version = "31.0.0" }
sp-std = { path = "../../../substrate/primitives/std", default-features = false, version = "14.0.0" }
sp-trie = { path = "../../../substrate/primitives/trie", default-features = false, version = "29.0.0" }

# Optional Benchmarking Dependencies
bp-test-utils = { path = "../../primitives/test-utils", default-features = false, optional = true, version = "0.7.0" }
frame-benchmarking = { path = "../../../substrate/frame/benchmarking", default-features = false, optional = true, version = "28.0.0" }

[dev-dependencies]
sp-core = { path = "../../../substrate/primitives/core" }
sp-io = { path = "../../../substrate/primitives/io" }

[features]
default = ["std"]
std = [
	"bp-header-chain/std",
	"bp-runtime/std",
	"bp-test-utils/std",
	"codec/std",
	"finality-grandpa/std",
	"frame-benchmarking/std",
	"frame-support/std",
	"frame-system/std",
	"log/std",
	"scale-info/std",
	"sp-consensus-grandpa/std",
	"sp-runtime/std",
	"sp-std/std",
	"sp-trie/std",
]
runtime-benchmarks = [
	"bp-test-utils",
	"frame-benchmarking/runtime-benchmarks",
	"frame-support/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
]
try-runtime = [
	"frame-support/try-runtime",
	"frame-system/try-runtime",
	"sp-runtime/try-runtime",
]
