[package]
name = "cumulus-client-network"
version = "0.7.0"
authors.workspace = true
description = "Cumulus-specific networking protocol"
edition.workspace = true
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"

[lints]
workspace = true

[dependencies]
async-trait = "0.1.74"
codec = { package = "parity-scale-codec", version = "3.0.0", features = ["derive"] }
futures = "0.3.28"
futures-timer = "3.0.2"
parking_lot = "0.12.1"
tracing = "0.1.37"
sc-client-api = { version = "28.0.0", path = "../../../substrate/client/api" }
sp-blockchain = { version = "28.0.0", path = "../../../substrate/primitives/blockchain" }
sp-consensus = { version = "0.32.0", path = "../../../substrate/primitives/consensus/common" }
sp-core = { version = "28.0.0", path = "../../../substrate/primitives/core" }
sp-runtime = { version = "31.0.0", path = "../../../substrate/primitives/runtime" }
sp-state-machine = { version = "0.35.0", path = "../../../substrate/primitives/state-machine" }
polkadot-node-primitives = { version = "7.0.0", path = "../../../polkadot/node/primitives" }
polkadot-parachain-primitives = { version = "6.0.0", path = "../../../polkadot/parachain" }
polkadot-primitives = { version = "7.0.0", path = "../../../polkadot/primitives" }
cumulus-relay-chain-interface = { version = "0.7.0", path = "../relay-chain-interface" }

[dev-dependencies]
portpicker = "0.1.1"
tokio = { version = "1.32.0", features = ["macros"] }
url = "2.4.0"
sc-cli = { path = "../../../substrate/client/cli" }
sc-client-api = { path = "../../../substrate/client/api" }
sp-consensus = { path = "../../../substrate/primitives/consensus/common" }
sp-core = { path = "../../../substrate/primitives/core" }
sp-keyring = { path = "../../../substrate/primitives/keyring" }
sp-keystore = { path = "../../../substrate/primitives/keystore" }
substrate-test-utils = { path = "../../../substrate/test-utils" }
polkadot-test-client = { path = "../../../polkadot/node/test/client" }
cumulus-primitives-core = { path = "../../primitives/core" }
cumulus-relay-chain-inprocess-interface = { path = "../relay-chain-inprocess-interface" }
cumulus-test-service = { path = "../../test/service" }
