[package]
name = "staging-chain-spec-builder"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
build = "build.rs"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
homepage = "https://substrate.io"
repository.workspace = true
publish = false
description = "staging-chain-spec-builder"

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[[bin]]
path = "bin/main.rs"
name = "chain-spec-builder"

[lib]
crate-type = ["rlib"]

[dependencies]
clap = { version = "4.4.14", features = ["derive"] }
log = "0.4.17"
sc-chain-spec = { version = "27.0.0", path = "../../../client/chain-spec" }
serde_json = "1.0.111"
sp-tracing = { version = "16.0.0", path = "../../../primitives/tracing" }
