[package]
name = "generate-bags"
version = "28.0.0"
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
homepage = "https://substrate.io"
repository.workspace = true
description = "Bag threshold generation script for pallet-bag-list"

[lints]
workspace = true

[dependencies]
frame-support = { version = "28.0.0", path = "../../../frame/support" }
frame-election-provider-support = { version = "28.0.0", path = "../../../frame/election-provider-support" }
frame-system = { version = "28.0.0", path = "../../../frame/system" }
pallet-staking = { version = "28.0.1", path = "../../../frame/staking" }
sp-staking = { version = "26.0.0", path = "../../../primitives/staking" }

# third party
chrono = { version = "0.4.31" }
num-format = "0.4.3"
