[package]
name = "pallet-transaction-payment-rpc"
version = "30.0.0"
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
homepage = "https://substrate.io"
repository.workspace = true
description = "RPC interface for the transaction payment pallet."
readme = "README.md"

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "3.6.1" }
jsonrpsee = { version = "0.16.2", features = ["client-core", "macros", "server"] }
pallet-transaction-payment-rpc-runtime-api = { version = "28.0.0", path = "runtime-api" }
sp-api = { version = "26.0.0", path = "../../../primitives/api" }
sp-blockchain = { version = "28.0.0", path = "../../../primitives/blockchain" }
sp-core = { version = "28.0.0", path = "../../../primitives/core" }
sp-rpc = { version = "26.0.0", path = "../../../primitives/rpc" }
sp-runtime = { version = "31.0.0", path = "../../../primitives/runtime" }
sp-weights = { version = "27.0.0", path = "../../../primitives/weights" }
