[package]
name = "bridge-hub-rococo-emulated-chain"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
description = "Bridge Hub Rococo emulated chain"
publish = false

[lints]
workspace = true

[dependencies]
serde_json = "1.0.111"

# Substrate
sp-core = { path = "../../../../../../../../substrate/primitives/core", default-features = false, version = "28.0.0" }
sp-runtime = { path = "../../../../../../../../substrate/primitives/runtime", default-features = false, version = "31.0.0" }
frame-support = { path = "../../../../../../../../substrate/frame/support", default-features = false, version = "28.0.0" }
parachains-common = { version = "7.0.0", path = "../../../../../../common" }

# Cumulus
cumulus-primitives-core = { path = "../../../../../../../primitives/core", default-features = false, version = "0.7.0" }
emulated-integration-tests-common = { path = "../../../../common", default-features = false, version = "3.0.0" }
bridge-hub-rococo-runtime = { version = "0.1.0", path = "../../../../../../runtimes/bridge-hubs/bridge-hub-rococo" }
bridge-hub-common = { path = "../../../../../../runtimes/bridge-hubs/common", default-features = false, version = "0.1.0" }

# Snowbridge
snowbridge-core = { path = "../../../../../../../../bridges/snowbridge/parachain/primitives/core", default-features = false, version = "0.1.0" }
snowbridge-router-primitives = { path = "../../../../../../../../bridges/snowbridge/parachain/primitives/router", default-features = false, version = "0.1.0" }
snowbridge-system = { path = "../../../../../../../../bridges/snowbridge/parachain/pallets/system", default-features = false, version = "0.1.0" }
snowbridge-inbound-queue = { path = "../../../../../../../../bridges/snowbridge/parachain/pallets/inbound-queue", default-features = false, version = "0.1.0" }
snowbridge-outbound-queue = { path = "../../../../../../../../bridges/snowbridge/parachain/pallets/outbound-queue", default-features = false, version = "0.1.0" }
