[package]
name = "cumulus-client-consensus-common"
description = "Cumulus specific common consensus implementations"
version = "0.7.0"
authors.workspace = true
edition.workspace = true
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"

[lints]
workspace = true

[dependencies]
async-trait = "0.1.74"
codec = { package = "parity-scale-codec", version = "3.0.0", features = ["derive"] }
dyn-clone = "1.0.16"
futures = "0.3.28"
log = "0.4.20"
tracing = "0.1.37"
sc-client-api = { version = "28.0.0", path = "../../../../substrate/client/api" }
sc-consensus = { version = "0.33.0", path = "../../../../substrate/client/consensus/common" }
sc-consensus-babe = { version = "0.34.0", path = "../../../../substrate/client/consensus/babe" }
sp-blockchain = { version = "28.0.0", path = "../../../../substrate/primitives/blockchain" }
sp-consensus = { version = "0.32.0", path = "../../../../substrate/primitives/consensus/common" }
sp-consensus-slots = { version = "0.32.0", path = "../../../../substrate/primitives/consensus/slots" }
sp-core = { version = "28.0.0", path = "../../../../substrate/primitives/core" }
sp-runtime = { version = "31.0.0", path = "../../../../substrate/primitives/runtime" }
sp-timestamp = { version = "26.0.0", path = "../../../../substrate/primitives/timestamp" }
sp-trie = { version = "29.0.0", path = "../../../../substrate/primitives/trie" }
substrate-prometheus-endpoint = { version = "0.17.0", path = "../../../../substrate/utils/prometheus" }
polkadot-primitives = { version = "7.0.0", path = "../../../../polkadot/primitives" }
cumulus-primitives-core = { version = "0.7.0", path = "../../../primitives/core" }
cumulus-relay-chain-interface = { version = "0.7.0", path = "../../relay-chain-interface" }
cumulus-client-pov-recovery = { version = "0.7.0", path = "../../pov-recovery" }
schnellru = "0.2.1"

[dev-dependencies]
futures-timer = "3.0.2"
sp-tracing = { path = "../../../../substrate/primitives/tracing" }
cumulus-test-client = { path = "../../../test/client" }
cumulus-test-relay-sproof-builder = { path = "../../../test/relay-sproof-builder" }
