[package]
name = "pallet-beefy"
version = "28.0.0"
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
repository.workspace = true
description = "BEEFY FRAME pallet"
homepage = "https://substrate.io"

[lints]
workspace = true

[dependencies]
codec = { package = "parity-scale-codec", version = "3.6.1", default-features = false, features = ["derive"] }
log = { version = "0.4.17", default-features = false }
scale-info = { version = "2.10.0", default-features = false, features = ["derive", "serde"] }
serde = { version = "1.0.195", optional = true }
frame-support = { path = "../support", default-features = false, version = "28.0.0" }
frame-system = { path = "../system", default-features = false, version = "28.0.0" }
pallet-authorship = { path = "../authorship", default-features = false, version = "28.0.0" }
pallet-session = { path = "../session", default-features = false, version = "28.0.0" }
sp-consensus-beefy = { path = "../../primitives/consensus/beefy", default-features = false, features = ["serde"], version = "13.0.0" }
sp-runtime = { path = "../../primitives/runtime", default-features = false, features = ["serde"], version = "31.0.0" }
sp-session = { path = "../../primitives/session", default-features = false, version = "27.0.0" }
sp-staking = { path = "../../primitives/staking", default-features = false, features = ["serde"], version = "26.0.0" }
sp-std = { path = "../../primitives/std", default-features = false, version = "14.0.0" }

[dev-dependencies]
frame-election-provider-support = { path = "../election-provider-support" }
pallet-balances = { path = "../balances" }
pallet-offences = { path = "../offences" }
pallet-staking = { path = "../staking" }
pallet-staking-reward-curve = { path = "../staking/reward-curve" }
pallet-timestamp = { path = "../timestamp" }
sp-core = { path = "../../primitives/core" }
sp-io = { path = "../../primitives/io" }
sp-staking = { path = "../../primitives/staking" }
sp-state-machine = { path = "../../primitives/state-machine", default-features = false }

[features]
default = ["std"]
std = [
	"codec/std",
	"frame-support/std",
	"frame-system/std",
	"log/std",
	"pallet-authorship/std",
	"pallet-session/std",
	"scale-info/std",
	"serde/std",
	"sp-consensus-beefy/std",
	"sp-runtime/std",
	"sp-session/std",
	"sp-staking/std",
	"sp-std/std",
]
try-runtime = [
	"frame-support/try-runtime",
	"frame-system/try-runtime",
	"pallet-authorship/try-runtime",
	"pallet-session/try-runtime",
	"sp-runtime/try-runtime",
]
