[package]
name = "substrate-frame-rpc-system"
version = "28.0.0"
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
homepage = "https://substrate.io"
repository.workspace = true
description = "FRAME's system exposed over Substrate RPC"
readme = "README.md"

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "3.6.1" }
jsonrpsee = { version = "0.16.2", features = ["client-core", "macros", "server"] }
futures = "0.3.21"
log = "0.4.17"
frame-system-rpc-runtime-api = { version = "26.0.0", path = "../../../../frame/system/rpc/runtime-api" }
sc-rpc-api = { version = "0.33.0", path = "../../../../client/rpc-api" }
sc-transaction-pool-api = { version = "28.0.0", path = "../../../../client/transaction-pool/api" }
sp-api = { version = "26.0.0", path = "../../../../primitives/api" }
sp-block-builder = { version = "26.0.0", path = "../../../../primitives/block-builder" }
sp-blockchain = { version = "28.0.0", path = "../../../../primitives/blockchain" }
sp-core = { version = "28.0.0", path = "../../../../primitives/core" }
sp-runtime = { version = "31.0.0", path = "../../../../primitives/runtime" }

[dev-dependencies]
sc-transaction-pool = { path = "../../../../client/transaction-pool" }
tokio = "1.22.0"
assert_matches = "1.3.0"
sp-tracing = { path = "../../../../primitives/tracing" }
substrate-test-runtime-client = { path = "../../../../test-utils/runtime/client" }
