[package]
name = "sp-api"
version = "26.0.0"
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
homepage = "https://substrate.io"
repository.workspace = true
description = "Substrate runtime api primitives"
readme = "README.md"

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "3.6.1", default-features = false }
sp-api-proc-macro = { version = "15.0.0", path = "proc-macro" }
sp-core = { path = "../core", default-features = false, version = "28.0.0" }
sp-std = { path = "../std", default-features = false, version = "14.0.0" }
sp-runtime = { path = "../runtime", default-features = false, version = "31.0.0" }
sp-externalities = { path = "../externalities", default-features = false, optional = true, version = "0.25.0" }
sp-version = { path = "../version", default-features = false, version = "29.0.0" }
sp-state-machine = { path = "../state-machine", default-features = false, optional = true, version = "0.35.0" }
sp-trie = { path = "../trie", default-features = false, optional = true, version = "29.0.0" }
hash-db = { version = "0.16.0", optional = true }
thiserror = { version = "1.0.48", optional = true }
scale-info = { version = "2.10.0", default-features = false, features = ["derive"] }
sp-metadata-ir = { path = "../metadata-ir", default-features = false, optional = true, version = "0.6.0" }
log = { version = "0.4.17", default-features = false }

[dev-dependencies]
sp-test-primitives = { path = "../test-primitives" }

[features]
default = ["std"]
std = [
	"codec/std",
	"hash-db",
	"log/std",
	"scale-info/std",
	"sp-api-proc-macro/std",
	"sp-core/std",
	"sp-externalities",
	"sp-externalities?/std",
	"sp-metadata-ir?/std",
	"sp-runtime/std",
	"sp-state-machine/std",
	"sp-std/std",
	"sp-trie/std",
	"sp-version/std",
	"thiserror",
]
# Special feature to disable logging completely.
#
# By default `sp-api` initializes the `RuntimeLogger` for each runtime api function. However,
# logging functionality increases the code size. It is recommended to enable this feature when
# building a runtime for registering it on chain.
#
# This sets the max logging level to `off` for `log`.
disable-logging = ["log/max_level_off"]
# Do not report the documentation in the metadata.
no-metadata-docs = ["sp-api-proc-macro/no-metadata-docs"]
frame-metadata = ["sp-api-proc-macro/frame-metadata", "sp-metadata-ir"]
