[package]
name = "pallet-bags-list-fuzzer"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
homepage = "https://substrate.io"
repository.workspace = true
description = "Fuzzer for FRAME pallet bags list"
publish = false

[lints]
workspace = true

[dependencies]
honggfuzz = "0.5"
rand = { version = "0.8", features = ["small_rng", "std"] }
frame-election-provider-support = { path = "../../election-provider-support", features = ["fuzz"], version = "28.0.0" }
pallet-bags-list = { path = "..", features = ["fuzz"], version = "27.0.0" }

[[bin]]
name = "bags-list"
path = "src/main.rs"
