[package]
name = "sc-transaction-pool"
version = "28.0.0"
authors.workspace = true
edition.workspace = true
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
homepage = "https://substrate.io"
repository.workspace = true
description = "Substrate transaction pool implementation."
readme = "README.md"

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
async-trait = "0.1.74"
codec = { package = "parity-scale-codec", version = "3.6.1" }
futures = "0.3.21"
futures-timer = "3.0.2"
linked-hash-map = "0.5.4"
log = "0.4.17"
parking_lot = "0.12.1"
serde = { version = "1.0.195", features = ["derive"] }
thiserror = "1.0.48"
prometheus-endpoint = { package = "substrate-prometheus-endpoint", path = "../../utils/prometheus", version = "0.17.0" }
sc-client-api = { version = "28.0.0", path = "../api" }
sc-transaction-pool-api = { version = "28.0.0", path = "api" }
sc-utils = { version = "14.0.0", path = "../utils" }
sp-api = { version = "26.0.0", path = "../../primitives/api" }
sp-blockchain = { version = "28.0.0", path = "../../primitives/blockchain" }
sp-core = { version = "28.0.0", path = "../../primitives/core" }
sp-runtime = { version = "31.0.0", path = "../../primitives/runtime" }
sp-tracing = { version = "16.0.0", path = "../../primitives/tracing" }
sp-transaction-pool = { version = "26.0.0", path = "../../primitives/transaction-pool" }

[dev-dependencies]
array-bytes = "6.1"
assert_matches = "1.3.0"
criterion = "0.4.0"
sc-block-builder = { path = "../block-builder" }
sp-consensus = { path = "../../primitives/consensus/common" }
substrate-test-runtime = { path = "../../test-utils/runtime" }
substrate-test-runtime-client = { path = "../../test-utils/runtime/client" }
substrate-test-runtime-transaction-pool = { path = "../../test-utils/runtime/transaction-pool" }

[[bench]]
name = "basics"
harness = false
