[package]
name = "parachain-template-node"
version = "0.1.0"
authors = ["Anonymous"]
description = "A new Cumulus FRAME-based Substrate Node, ready for hacking together a parachain."
license = "Unlicense"
homepage = "https://substrate.io"
repository.workspace = true
edition.workspace = true
build = "build.rs"
publish = false

[lints]
workspace = true

[dependencies]
clap = { version = "4.4.14", features = ["derive"] }
log = "0.4.20"
codec = { package = "parity-scale-codec", version = "3.0.0" }
serde = { version = "1.0.195", features = ["derive"] }
jsonrpsee = { version = "0.16.2", features = ["server"] }
futures = "0.3.28"
serde_json = "1.0.111"
parachain-template-runtime = { version = "0.7.0", path = "../runtime" }
frame-benchmarking = { version = "28.0.0", path = "../../../substrate/frame/benchmarking" }
frame-benchmarking-cli = { version = "32.0.0", path = "../../../substrate/utils/frame/benchmarking-cli" }
pallet-transaction-payment-rpc = { version = "30.0.0", path = "../../../substrate/frame/transaction-payment/rpc" }
sc-basic-authorship = { version = "0.34.0", path = "../../../substrate/client/basic-authorship" }
sc-chain-spec = { version = "27.0.0", path = "../../../substrate/client/chain-spec" }
sc-cli = { version = "0.36.0", path = "../../../substrate/client/cli" }
sc-client-api = { version = "28.0.0", path = "../../../substrate/client/api" }
sc-offchain = { version = "29.0.0", path = "../../../substrate/client/offchain" }
sc-consensus = { version = "0.33.0", path = "../../../substrate/client/consensus/common" }
sc-executor = { version = "0.32.0", path = "../../../substrate/client/executor" }
sc-network = { version = "0.34.0", path = "../../../substrate/client/network" }
sc-network-sync = { version = "0.33.0", path = "../../../substrate/client/network/sync" }
sc-rpc = { version = "29.0.0", path = "../../../substrate/client/rpc" }
sc-service = { version = "0.35.0", path = "../../../substrate/client/service" }
sc-sysinfo = { version = "27.0.0", path = "../../../substrate/client/sysinfo" }
sc-telemetry = { version = "15.0.0", path = "../../../substrate/client/telemetry" }
sc-tracing = { version = "28.0.0", path = "../../../substrate/client/tracing" }
sc-transaction-pool = { version = "28.0.0", path = "../../../substrate/client/transaction-pool" }
sc-transaction-pool-api = { version = "28.0.0", path = "../../../substrate/client/transaction-pool/api" }
sp-api = { version = "26.0.0", path = "../../../substrate/primitives/api" }
sp-block-builder = { version = "26.0.0", path = "../../../substrate/primitives/block-builder" }
sp-blockchain = { version = "28.0.0", path = "../../../substrate/primitives/blockchain" }
sp-consensus-aura = { version = "0.32.0", path = "../../../substrate/primitives/consensus/aura" }
sp-core = { version = "28.0.0", path = "../../../substrate/primitives/core" }
sp-keystore = { version = "0.34.0", path = "../../../substrate/primitives/keystore" }
sp-io = { version = "30.0.0", path = "../../../substrate/primitives/io" }
sp-runtime = { version = "31.0.0", path = "../../../substrate/primitives/runtime" }
sp-timestamp = { version = "26.0.0", path = "../../../substrate/primitives/timestamp" }
substrate-frame-rpc-system = { version = "28.0.0", path = "../../../substrate/utils/frame/rpc/system" }
substrate-prometheus-endpoint = { version = "0.17.0", path = "../../../substrate/utils/prometheus" }

# Polkadot
polkadot-cli = { path = "../../../polkadot/cli", features = ["rococo-native"], version = "7.0.0" }
polkadot-primitives = { version = "7.0.0", path = "../../../polkadot/primitives" }
xcm = { package = "staging-xcm", path = "../../../polkadot/xcm", default-features = false, version = "7.0.0" }
cumulus-client-cli = { version = "0.7.0", path = "../../client/cli" }
cumulus-client-collator = { version = "0.7.0", path = "../../client/collator" }
cumulus-client-consensus-aura = { version = "0.7.0", path = "../../client/consensus/aura" }
cumulus-client-consensus-common = { version = "0.7.0", path = "../../client/consensus/common" }
cumulus-client-consensus-proposer = { version = "0.7.0", path = "../../client/consensus/proposer" }
cumulus-client-service = { version = "0.7.0", path = "../../client/service" }
cumulus-primitives-core = { version = "0.7.0", path = "../../primitives/core" }
cumulus-primitives-parachain-inherent = { version = "0.7.0", path = "../../primitives/parachain-inherent" }
cumulus-relay-chain-interface = { version = "0.7.0", path = "../../client/relay-chain-interface" }
color-print = "0.3.4"

[build-dependencies]
substrate-build-script-utils = { version = "11.0.0", path = "../../../substrate/utils/build-script-utils" }

[features]
default = []
runtime-benchmarks = [
	"cumulus-primitives-core/runtime-benchmarks",
	"frame-benchmarking-cli/runtime-benchmarks",
	"frame-benchmarking/runtime-benchmarks",
	"parachain-template-runtime/runtime-benchmarks",
	"polkadot-cli/runtime-benchmarks",
	"polkadot-primitives/runtime-benchmarks",
	"sc-service/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
]
try-runtime = [
	"parachain-template-runtime/try-runtime",
	"polkadot-cli/try-runtime",
	"sp-runtime/try-runtime",
]
