[package]
name = "bridge-hub-westend-emulated-chain"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
description = "Bridge Hub Westend emulated chain"
publish = false

[lints]
workspace = true

[dependencies]
serde_json = "1.0.111"

# Substrate
sp-core = { path = "../../../../../../../../substrate/primitives/core", default-features = false, version = "28.0.0" }
sp-runtime = { path = "../../../../../../../../substrate/primitives/runtime", default-features = false, version = "31.0.0" }
frame-support = { path = "../../../../../../../../substrate/frame/support", default-features = false, version = "28.0.0" }
parachains-common = { version = "7.0.0", path = "../../../../../../common" }

# Cumulus
cumulus-primitives-core = { path = "../../../../../../../primitives/core", default-features = false, version = "0.7.0" }
emulated-integration-tests-common = { path = "../../../../common", default-features = false, version = "3.0.0" }
bridge-hub-westend-runtime = { version = "0.1.0", path = "../../../../../../runtimes/bridge-hubs/bridge-hub-westend" }
bridge-hub-common = { path = "../../../../../../runtimes/bridge-hubs/common", default-features = false, version = "0.1.0" }
