[package]
name = "substrate-test-runtime-transaction-pool"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
homepage = "https://substrate.io"
repository.workspace = true
publish = false
description = "substrate-test-runtime-transaction-pool"

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "3.6.1" }
futures = "0.3.21"
parking_lot = "0.12.1"
thiserror = "1.0"
sc-transaction-pool = { version = "28.0.0", path = "../../../client/transaction-pool" }
sc-transaction-pool-api = { version = "28.0.0", path = "../../../client/transaction-pool/api" }
sp-blockchain = { version = "28.0.0", path = "../../../primitives/blockchain" }
sp-runtime = { version = "31.0.0", path = "../../../primitives/runtime" }
substrate-test-runtime-client = { version = "0.1.0", path = "../client" }
