[package]
description = "Substrate offchain workers primitives"
name = "sp-offchain"
version = "26.0.0"
license = "Apache-2.0"
authors.workspace = true
edition.workspace = true
homepage = "https://substrate.io"
repository.workspace = true
readme = "README.md"

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
sp-api = { path = "../api", default-features = false, version = "26.0.0" }
sp-core = { path = "../core", default-features = false, version = "28.0.0" }
sp-runtime = { path = "../runtime", default-features = false, version = "31.0.0" }

[features]
default = ["std"]
std = ["sp-api/std", "sp-core/std", "sp-runtime/std"]
