[package]
name = "snowbridge-outbound-queue"
description = "Snowbridge Outbound Queue"
version = "0.1.0"
edition = "2021"
authors = ["Snowfork <contact@snowfork.com>"]
repository = "https://github.com/Snowfork/snowbridge"
license = "Apache-2.0"
publish = false

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
serde = { version = "1.0.195", features = ["alloc", "derive"], default-features = false }
codec = { version = "3.6.1", package = "parity-scale-codec", default-features = false, features = ["derive"] }
scale-info = { version = "2.9.0", default-features = false, features = ["derive"] }
hex-literal = { version = "0.4.1", optional = true }

frame-benchmarking = { path = "../../../../../substrate/frame/benchmarking", default-features = false, optional = true, version = "28.0.0" }
frame-support = { path = "../../../../../substrate/frame/support", default-features = false, version = "28.0.0" }
frame-system = { path = "../../../../../substrate/frame/system", default-features = false, version = "28.0.0" }
sp-core = { path = "../../../../../substrate/primitives/core", default-features = false, version = "28.0.0" }
sp-std = { path = "../../../../../substrate/primitives/std", default-features = false, version = "14.0.0" }
sp-runtime = { path = "../../../../../substrate/primitives/runtime", default-features = false, version = "31.0.0" }
sp-io = { path = "../../../../../substrate/primitives/io", default-features = false, version = "30.0.0" }
sp-arithmetic = { path = "../../../../../substrate/primitives/arithmetic", default-features = false, version = "23.0.0" }

bridge-hub-common = { path = "../../../../../cumulus/parachains/runtimes/bridge-hubs/common", default-features = false, version = "0.1.0" }

snowbridge-core = { path = "../../primitives/core", features = ["serde"], default-features = false, version = "0.1.0" }
snowbridge-outbound-queue-merkle-tree = { path = "merkle-tree", default-features = false, version = "0.1.1" }
ethabi = { git = "https://github.com/snowfork/ethabi-decode.git", package = "ethabi-decode", branch = "master", default-features = false }

xcm = { package = "staging-xcm", path = "../../../../../polkadot/xcm", default-features = false, version = "7.0.0" }

[dev-dependencies]
pallet-message-queue = { path = "../../../../../substrate/frame/message-queue", default-features = false }
sp-keyring = { path = "../../../../../substrate/primitives/keyring" }
hex-literal = { version = "0.4.1" }

[features]
default = ["std"]
std = [
	"bridge-hub-common/std",
	"codec/std",
	"ethabi/std",
	"frame-benchmarking/std",
	"frame-support/std",
	"frame-system/std",
	"scale-info/std",
	"serde/std",
	"snowbridge-core/std",
	"snowbridge-outbound-queue-merkle-tree/std",
	"sp-arithmetic/std",
	"sp-core/std",
	"sp-io/std",
	"sp-runtime/std",
	"sp-std/std",
	"xcm/std",
]
runtime-benchmarks = [
	"bridge-hub-common/runtime-benchmarks",
	"frame-benchmarking",
	"frame-benchmarking/runtime-benchmarks",
	"frame-support/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
	"hex-literal",
	"snowbridge-core/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
]
try-runtime = [
	"frame-support/try-runtime",
	"frame-system/try-runtime",
	"sp-runtime/try-runtime",
]
