[package]
name = "pallet-paged-list-fuzzer"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
homepage = "https://substrate.io"
repository.workspace = true
description = "Fuzz storage types of pallet-paged-list"
publish = false

[lints]
workspace = true

[[bin]]
name = "pallet-paged-list-fuzzer"
path = "src/paged_list.rs"

[dependencies]
arbitrary = "1.3.0"
honggfuzz = "0.5.49"

frame-support = { path = "../../support", default-features = false, features = ["std"], version = "28.0.0" }
sp-io = { path = "../../../primitives/io", default-features = false, features = ["std"], version = "30.0.0" }
pallet-paged-list = { path = "..", default-features = false, features = ["std"], version = "0.6.0" }
