[package]
name = "polkadot-node-core-candidate-validation"
description = "Polkadot crate that implements the Candidate Validation subsystem. Handles requests to validate candidates according to a PVF."
version = "7.0.0"
authors.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
async-trait = "0.1.74"
futures = "0.3.21"
futures-timer = "3.0.2"
gum = { package = "tracing-gum", path = "../../gum", version = "7.0.0" }

sp-maybe-compressed-blob = { package = "sp-maybe-compressed-blob", path = "../../../../substrate/primitives/maybe-compressed-blob", version = "11.0.0" }
parity-scale-codec = { version = "3.6.1", default-features = false, features = ["bit-vec", "derive"] }
polkadot-primitives = { version = "7.0.0", path = "../../../primitives" }
polkadot-parachain-primitives = { version = "6.0.0", path = "../../../parachain" }
polkadot-node-primitives = { version = "7.0.0", path = "../../primitives" }
polkadot-node-subsystem = { version = "7.0.0", path = "../../subsystem" }
polkadot-node-subsystem-util = { version = "7.0.0", path = "../../subsystem-util" }
polkadot-node-metrics = { version = "7.0.0", path = "../../metrics" }
polkadot-overseer = { version = "7.0.0", path = "../../overseer" }

[target.'cfg(not(any(target_os = "android", target_os = "unknown")))'.dependencies]
polkadot-node-core-pvf = { version = "7.0.0", path = "../pvf" }

[dev-dependencies]
sp-keyring = { path = "../../../../substrate/primitives/keyring" }
futures = { version = "0.3.21", features = ["thread-pool"] }
assert_matches = "1.4.0"
polkadot-node-subsystem-test-helpers = { path = "../../subsystem-test-helpers" }
sp-core = { path = "../../../../substrate/primitives/core" }
test-helpers = { package = "polkadot-primitives-test-helpers", path = "../../../primitives/test-helpers" }
