[package]
name = "cumulus-primitives-aura"
version = "0.7.0"
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
description = "Core primitives for Aura in Cumulus"

[lints]
workspace = true

[dependencies]
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive"] }

# Substrate
sp-api = { path = "../../../substrate/primitives/api", default-features = false, version = "26.0.0" }
sp-consensus-aura = { path = "../../../substrate/primitives/consensus/aura", default-features = false, version = "0.32.0" }
sp-runtime = { path = "../../../substrate/primitives/runtime", default-features = false, version = "31.0.0" }
sp-std = { path = "../../../substrate/primitives/std", default-features = false, version = "14.0.0" }

# Polkadot
polkadot-core-primitives = { path = "../../../polkadot/core-primitives", default-features = false, version = "7.0.0" }
polkadot-primitives = { path = "../../../polkadot/primitives", default-features = false, version = "7.0.0" }

[features]
default = ["std"]
std = [
	"codec/std",
	"polkadot-core-primitives/std",
	"polkadot-primitives/std",
	"sp-api/std",
	"sp-consensus-aura/std",
	"sp-runtime/std",
	"sp-std/std",
]
