[package]
name = "sc-consensus-beefy"
version = "13.0.0"
authors.workspace = true
edition.workspace = true
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
repository.workspace = true
description = "BEEFY Client gadget for substrate"
homepage = "https://substrate.io"

[lints]
workspace = true

[dependencies]
array-bytes = "6.1"
async-channel = "1.8.0"
async-trait = "0.1.74"
codec = { package = "parity-scale-codec", version = "3.6.1", features = ["derive"] }
fnv = "1.0.6"
futures = "0.3"
log = "0.4"
parking_lot = "0.12.1"
thiserror = "1.0"
wasm-timer = "0.2.5"
prometheus = { package = "substrate-prometheus-endpoint", path = "../../../utils/prometheus", version = "0.17.0" }
sc-client-api = { version = "28.0.0", path = "../../api" }
sc-consensus = { version = "0.33.0", path = "../common" }
sc-network = { version = "0.34.0", path = "../../network" }
sc-network-gossip = { version = "0.34.0", path = "../../network-gossip" }
sc-network-sync = { version = "0.33.0", path = "../../network/sync" }
sc-utils = { version = "14.0.0", path = "../../utils" }
sp-api = { version = "26.0.0", path = "../../../primitives/api" }
sp-application-crypto = { version = "30.0.0", path = "../../../primitives/application-crypto" }
sp-arithmetic = { version = "23.0.0", path = "../../../primitives/arithmetic" }
sp-blockchain = { version = "28.0.0", path = "../../../primitives/blockchain" }
sp-consensus = { version = "0.32.0", path = "../../../primitives/consensus/common" }
sp-consensus-beefy = { version = "13.0.0", path = "../../../primitives/consensus/beefy" }
sp-core = { version = "28.0.0", path = "../../../primitives/core" }
sp-keystore = { version = "0.34.0", path = "../../../primitives/keystore" }
sp-mmr-primitives = { version = "26.0.0", path = "../../../primitives/merkle-mountain-range" }
sp-runtime = { version = "31.0.0", path = "../../../primitives/runtime" }
tokio = "1.22.0"


[dev-dependencies]
serde = "1.0.195"
tempfile = "3.1.0"
sc-block-builder = { path = "../../block-builder" }
sc-network-test = { path = "../../network/test" }
sp-consensus-grandpa = { path = "../../../primitives/consensus/grandpa" }
sp-keyring = { path = "../../../primitives/keyring" }
sp-tracing = { path = "../../../primitives/tracing" }
substrate-test-runtime-client = { path = "../../../test-utils/runtime/client" }
